import {useState, useEffect, useRef, useCallback} from "react";

var T="#00D4AA", BL="#38BDF8", V="#A78BFA", AM="#FBBF24", PK="#F472B6";
var BG="#060810", B2="#0B0F18", B3="#141924", TX="#E2E8F0", MT="#64748B", DM="#3B4559", BD="rgba(140,160,200,0.07)";
var hd={fontFamily:"'Outfit Variable',Outfit,system-ui",letterSpacing:"-.03em"};
var bn={display:"inline-flex",alignItems:"center",gap:6,padding:"12px 24px",background:T,color:BG,fontWeight:600,fontSize:14,border:"none",borderRadius:6,cursor:"pointer",fontFamily:"inherit"};
var b2={display:"inline-flex",alignItems:"center",gap:6,padding:"12px 24px",background:"transparent",color:TX,fontWeight:500,fontSize:14,border:"1px solid rgba(140,160,200,.15)",borderRadius:6,cursor:"pointer",fontFamily:"inherit"};
function Sc(p){return <section style={{borderTop:p.bt?"1px solid "+BD:"none",background:p.bg||"transparent"}}><div style={{maxWidth:960,margin:"0 auto",padding:"72px 40px"}}>{p.children}</div></section>}
function Tg(p){return <div style={{fontSize:11,textTransform:"uppercase",letterSpacing:3,color:p.c||T,marginBottom:12,fontWeight:500}}>{p.children}</div>}
function Rv(p){var r=useRef(null),v=useState(false);useEffect(function(){var el=r.current;if(!el)return;var o=new IntersectionObserver(function(e){if(e[0].isIntersecting){v[1](true);o.disconnect()}},{threshold:0.08});o.observe(el);return function(){o.disconnect()}},[]);return <div ref={r} style={{opacity:v[0]?1:0,transform:v[0]?"none":"translateY(24px)",transition:"all .7s cubic-bezier(.22,1,.36,1) "+(p.d||0)+"s"}}>{p.children}</div>}

var SOL=[
{id:"home",n:"Smart Home",ic:"□",ln:"Security · Senior care · Privacy-first",h:"Your cameras, doorbells, and sensors alert you 90 times a day. How many actually matter?",d:"You bought smart cameras, a video doorbell, motion sensors, maybe a smoke detector. None of them talk to each other. You get 90 notifications a day — 60% of owners mute everything within 90 days. The Sevyn8 Hub connects your existing devices into one intelligence layer. Or deploy new Sevyn8-powered smart devices with AI built in. Either way — decisions, not alerts.",wf:"Ring, Arlo, and TP-Link Tapo treat each device as an island. Camera alerts. Doorbell alerts. Sensor alerts. No correlation. When your WiFi drops, your security drops. They detect motion — not meaning. A delivery driver and a stranger at 3 AM trigger the exact same alert. No system fuses cameras, door sensors, and IoT into one intelligence.",
cs:["Knows your family — Recognises faces on-device. Family, friends, and regular delivery people never trigger an alert","Knows the difference — A person at 3 AM gets flagged. The same person at 3 PM with a package gets logged silently","Watches over elders — Fall detection, gait changes, and irregular routine alerts for elderly family members at home","Never uploads — All AI runs on the Hub device in your home. No footage goes to any cloud. No server. No one else sees it","Works without WiFi — Full intelligence runs offline. Your security does not depend on your internet connection"],
st:[{v:"97%",l:"Noise eliminated"},{v:"3-5",l:"Decisions per day"},{v:"0",l:"Data to cloud"},{v:"₹499",l:"Monthly option"}],
dp:["Connect the Sevyn8 Hub to your existing cameras, doorbells, and sensors — or deploy new Sevyn8-powered smart devices with AI built in.","The Hub learns your household — who comes and goes, what\u2019s normal, what isn\u2019t. Intelligence starts within hours.","90 daily alerts become 3-5 that genuinely matter. Open the app only when something real happens."],
dpl:["Your cameras, sensors, doorbell","Sevyn8 Hub","Your phone"],
scn:[{t:"8:47 AM",b:"Camera alert: motion detected at front door. It is the postman. You already left for work.",w:"Face recognised as regular delivery. Package logged. No alert sent."},{t:"2:15 PM",b:"Door sensor triggers. Cat pushed the back door. Alert #43 today.",w:"Pet movement pattern recognised. Door sensor + camera fused. Logged silently."},{t:"11:30 PM",b:"Motion alert #87. Neighbourhood cat on driveway. You muted alerts last week.",w:"Unknown person at side gate. Unusual hour. Single alert sent with face capture."}],
sens:["IP Cameras","Video Doorbell","Motion Sensors","Door/Window Sensors","Smoke Detectors","BLE Beacons"]},
{id:"retail",n:"Retail",ic:"◆",ln:"Shrinkage · Shelf compliance · Footfall",h:"200 cameras, ESL tags, and RFID readers across 40 stores. What are they actually doing for you?",d:"Your CCTV system cost crores to install. It records everything and understands nothing. Your LP team reviews maybe 5% of footage — after the fact. Shrinkage shows up in quarterly reports, not in real-time alerts. Sevyn8 deploys two ways: connect to your existing cameras and sensors, or deploy new intelligent cameras with AI built in. Either way, every device becomes an active loss prevention system.",wf:"Your current cameras are recording devices, not intelligence systems. Cloud analytics providers require constant connectivity and send your store footage to external servers. They cannot learn that Store #12 has a different pilferage pattern than Store #35 — each store starts from zero.",
cs:["Catches theft as it happens — Behavioural analysis detects concealment patterns in real time, not after quarterly stock-takes","Monitors every shelf — Planogram compliance verified every 15 minutes with instant deviation alerts to floor staff","Counts what matters — Zone-level footfall with 98%+ accuracy, dwell time, and conversion rate — not just door counts","Manages queues — Automatic alerts to open new counters when wait times exceed your defined thresholds","Learns across stores — What Store #1 catches, Store #40 already knows. Intelligence compounds across your entire network"],
st:[{v:"40-60%",l:"Shrinkage reduction"},{v:"98%+",l:"Footfall accuracy"},{v:"60 days",l:"Measurable results"},{v:"3-6×",l:"ROI in 6 months"}],
dp:["Connect to your existing cameras, ESL, and RFID — or deploy new intelligent cameras with AI on-board. We start with one floor, 10-20 devices.","Within 60 days, you see measurable shrinkage reduction, shelf compliance data, and zone-level footfall — on a dashboard your team actually uses.","Roll out to more stores. Store #50 inherits intelligence from stores #1 through #49. Every deployment makes the next one smarter."],
dpl:["Your CCTV + ESL + RFID","One Sevyn8 box per store","Your LP dashboard"],
scn:[{t:"10:23 AM",b:"Customer lingers at cosmetics shelf for 6 minutes. CCTV records it. Nobody sees it.",w:"Dwell time anomaly + repeated reach + no basket. Concealment alert to floor staff in real time."},{t:"2:45 PM",b:"Shelf gap in aisle 7 since morning. Discovered during evening walk.",w:"ESL + camera fusion detects planogram deviation at 10:15 AM. Auto-alert to merchandising team."},{t:"5:10 PM",b:"Long queue at counter 3. Customers walk out. You see it in tomorrow's conversion report.",w:"Queue length exceeds threshold. Alert to open counter 5. Footfall + dwell data updated live."}],
sens:["CCTV Cameras","Dome Cameras","ESL Tags","RFID Readers","Shelf-Edge Cameras","BLE Beacons"]},
{id:"fleet",n:"Fleet & Logistics",ic:"▲",ln:"Driver safety · Warehouse ops · Compliance",h:"GPS, dashcams, and facility sensors — four systems, four dashboards, zero intelligence.",d:"You track 500 vehicles by GPS. You know where they are but not whether the driver is awake, the cargo is secure, or your warehouse crew is wearing PPE. Compliance means audit day. Sevyn8 deploys two ways: add a box to your existing dashcams and facility cameras, or deploy new AI-enabled dashcams and sensors with on-board inference. Either way — safety becomes continuous, not periodic.",wf:"Your fleet telematics system tracks location and engine data. It cannot see inside the cabin, cannot verify PPE on the warehouse floor, and cannot predict equipment failure. Compliance happens during audits. Between audits, nobody is watching.",
cs:["Keeps drivers alert — Fatigue and distraction detected in real time with immediate in-cab audio intervention, before an incident occurs","Watches the road — Lane departure, tailgating, and forward collision warnings running on the dashcam itself, not a remote server","Verifies safety gear — Hard hats, vests, and gloves checked continuously on every person on the facility floor, every minute","Protects the floor — Forklift proximity warnings, restricted zone enforcement, loading dock monitoring, and near-miss tracking","Predicts breakdowns — Vibration and thermal patterns on fleet vehicles and warehouse equipment flag failures before they happen"],
st:[{v:"60%",l:"Fewer incidents"},{v:"100%",l:"Continuous compliance"},{v:"60 days",l:"POC results"},{v:"₹68-171L",l:"Annual contract"}],
dp:["Sevyn8 connects to your existing dashcams and facility cameras. Single facility or 50-vehicle fleet. No new hardware required.","Within 60 days — incident rates, compliance scores, near-miss tracking, and driver behaviour scores visible on one dashboard.","Expand across sites. Multi-facility patterns emerge that no single location can detect. Compliance becomes automated and auditable."],
dpl:["Dashcams + sensors + facility cameras","One Sevyn8 box per site","Your ops dashboard"],
scn:[{t:"2:17 AM",b:"Driver has been driving 7 hours. GPS shows he is on the highway. Nobody knows his eyes are closing.",w:"In-cab IR detects drowsiness at 3 seconds. Audio alert fires. Fleet manager notified. Near-miss logged."},{t:"9:40 AM",b:"Warehouse crew enters loading zone. Two without hard hats. Next audit is in 3 weeks.",w:"Camera + PPE model verifies every person entering the zone. Violation flagged instantly. Logged for compliance."},{t:"4:55 PM",b:"Forklift enters pedestrian zone. Near-miss. Nobody reports it.",w:"BLE proximity sensor + camera detect forklift in Zone C with pedestrians. Alert + incident log + fleet-wide pattern update."}],
sens:["Dashcams","In-Cab IR Cameras","Facility Cameras","Vibration Sensors","BLE Proximity Sensors","GPS/OBD Telematics"]},
{id:"coldchain",n:"Food & Cold Storage",ic:"○",ln:"Temperature AI · Contamination · FSSAI",h:"Thermal cameras, temperature loggers, humidity sensors — all recording separately. None predicting.",d:"Your cold storage facility runs temperature loggers that beep after the threshold is crossed — by then, the product is already compromised. FSSAI compliance is a clipboard exercise. Sevyn8 deploys two ways: connect to your existing thermal cameras and IoT sensors, or deploy new intelligent sensors with on-board AI. Either way — thermal, humidity, door, and vision data fuse into one platform that predicts breaches 15-30 minutes before they happen.",wf:"Your temperature loggers are reactive — they tell you what went wrong, not what\u2019s about to go wrong. CCTV is only reviewed after a contamination incident. FSSAI audit preparation takes weeks of assembling manual records. No existing system connects temperature, vision, and compliance on one platform.",
cs:["Predicts breaches — Thermal camera + IoT sensor fusion spots cold chain deviations 15-30 minutes before your threshold is crossed","Catches contamination — Vision AI identifies foreign objects on processing lines, pest intrusion, and hygiene violations in real time","Automates FSSAI — Worker hygiene, PPE compliance (hairnets, gloves, aprons), and sanitation protocols monitored continuously, not during audits","Enforces door discipline — Cold room door open-time tracked with immediate alerts when duration exceeds safe thresholds","Tracks inventory — FIFO compliance monitoring, expiry risk scoring, and stock rotation verification through camera analytics"],
st:[{v:"15-30min",l:"Early breach warning"},{v:"40-60%",l:"Loss reduction"},{v:"100%",l:"Automated FSSAI"},{v:"60 days",l:"Validated results"}],
dp:["Thermal cameras and IoT sensors deploy on your existing cold storage infrastructure. One facility. No structural changes required.","Within 60 days — breach prediction accuracy validated, contamination events tracked, FSSAI compliance dashboard generating automated reports.","Expand across facilities. Facility #10 benefits from temperature patterns learned across facilities #1-9. Audit prep drops from weeks to hours."],
dpl:["Thermal cameras + IoT sensors","One Sevyn8 box","Your compliance dashboard"],
scn:[{t:"6:12 AM",b:"Cold room door left open during shift change. Temperature logger beeps at 6:45 AM. Product already at risk.",w:"Door sensor + thermal camera + temperature probe fused. Deviation predicted at 6:14 AM. Alert sent. Door closed by 6:16 AM."},{t:"11:30 AM",b:"Worker enters processing area without hairnet. CCTV records it. Discovered during monthly FSSAI audit.",w:"Vision AI detects missing PPE in real time. Entry flagged. Compliance log updated automatically."},{t:"3:00 PM",b:"Humidity spike in Zone B. Nobody correlates it with the condenser issue logged separately.",w:"Humidity sensor + thermal camera + maintenance log fused. Condenser anomaly flagged. Predictive maintenance triggered."}],
sens:["Thermal LWIR Cameras","Temperature Probes","Humidity Sensors","Door Sensors","Processing Line Cameras","IoT Gateways"]},
];

function HeroAnim(){
  var cv=useRef(null);
  useEffect(function(){
    var c=cv.current;if(!c)return;
    var x=c.getContext("2d"),W,H,af,pts=[];
    var rs=function(){var d=Math.min(window.devicePixelRatio||1,2);W=c.offsetWidth;H=c.offsetHeight;c.width=W*d;c.height=H*d;x.setTransform(d,0,0,d,0,0)};
    var sp=function(sx,sy,ex,ey,cl){pts.push({sx:sx,sy:sy,ex:ex,ey:ey,t:-Math.random()*.3,c:cl,s:.005+Math.random()*.004})};
    var rgb=function(c2){return c2===T?"0,212,170":c2===BL?"56,189,248":c2===V?"167,139,250":c2===AM?"251,191,36":"244,114,182"};
    var rr=function(a,b,w,h,r){x.beginPath();x.moveTo(a+r,b);x.lineTo(a+w-r,b);x.quadraticCurveTo(a+w,b,a+w,b+r);x.lineTo(a+w,b+h-r);x.quadraticCurveTo(a+w,b+h,a+w-r,b+h);x.lineTo(a+r,b+h);x.quadraticCurveTo(a,b+h,a,b+h-r);x.lineTo(a,b+r);x.quadraticCurveTo(a,b,a+r,b);x.closePath()};
    var oc=[T,AM,V,BL];
    var draw=function(t){
      x.clearRect(0,0,W,H);var s=t*.001;
      var bx=W*.5,by=H*.5,bw=130,bh=170;
      var gp=.5+Math.sin(s*1.3)*.2;
      x.shadowColor="rgba(0,212,170,"+(0.15*gp)+")";x.shadowBlur=50;
      rr(bx-bw/2,by-bh/2,bw,bh,14);x.fillStyle=B2;x.fill();x.shadowBlur=0;
      x.strokeStyle="rgba(0,212,170,"+(0.3+gp*.15)+")";x.lineWidth=1.2;x.stroke();
      x.setLineDash([3,5]);x.lineWidth=.5;
      for(var i=0;i<4;i++){var ly=H*(.15+i*.23);x.beginPath();x.moveTo(10,ly);var mx=(10+bx-bw/2)/2;x.bezierCurveTo(mx,ly,mx,by+(i-1.5)*20,bx-bw/2,by+(i-1.5)*20);x.strokeStyle="rgba(0,212,170,.08)";x.stroke();if(Math.random()<.03)sp(10,ly,bx-bw/2,by+(i-1.5)*20,T)}
      for(var i=0;i<4;i++){var ry=H*(.15+i*.23);x.beginPath();x.moveTo(bx+bw/2,by+(i-1.5)*20);var mx2=(bx+bw/2+W-10)/2;x.bezierCurveTo(mx2,by+(i-1.5)*20,mx2,ry,W-10,ry);x.strokeStyle="rgba("+rgb(oc[i])+",.06)";x.stroke();if(Math.random()<.02)sp(bx+bw/2,by+(i-1.5)*20,W-10,ry,oc[i])}
      x.setLineDash([]);
      for(var i=pts.length-1;i>=0;i--){var p=pts[i];p.t+=p.s;if(p.t>1){pts.splice(i,1);continue}if(p.t<0)continue;var e=p.t<.5?2*p.t*p.t:1-Math.pow(-2*p.t+2,2)/2;var px=p.sx+(p.ex-p.sx)*e,py=p.sy+(p.ey-p.sy)*e+Math.sin(e*Math.PI*3)*6;var al=Math.sin(p.t*Math.PI),r2=rgb(p.c);x.shadowColor="rgba("+r2+",.5)";x.shadowBlur=8;x.beginPath();x.arc(px,py,2.5,0,Math.PI*2);x.fillStyle="rgba("+r2+","+al*.85+")";x.fill();x.shadowBlur=0;for(var j=1;j<=3;j++){var tr=Math.max(0,p.t-j*.02),te=tr<.5?2*tr*tr:1-Math.pow(-2*tr+2,2)/2;x.beginPath();x.arc(p.sx+(p.ex-p.sx)*te,p.sy+(p.ey-p.sy)*te+Math.sin(te*Math.PI*3)*6,1.8-j*.35,0,Math.PI*2);x.fillStyle="rgba("+r2+","+al*.12*(1-j/3)+")";x.fill()}}
      af=requestAnimationFrame(draw)};
    rs();af=requestAnimationFrame(draw);window.addEventListener("resize",rs);
    return function(){cancelAnimationFrame(af);window.removeEventListener("resize",rs)};
  },[]);
  var devs=["IP Camera","Thermal","IoT Sensor","PTZ Camera"];
  var outs=[{l:"Dashboard",c:T},{l:"Smart Alert",c:AM},{l:"OTA Update",c:V},{l:"Partner API",c:BL}];
  var lb={position:"absolute",padding:"8px 14px",borderRadius:7,background:B3,fontSize:13,fontWeight:600,color:"#94A3B8",whiteSpace:"nowrap",border:"1px solid rgba(0,212,170,.18)",zIndex:3};
  return (<div style={{position:"relative",width:"100%",height:"100%"}}>
    <canvas ref={cv} style={{position:"absolute",inset:0,width:"100%",height:"100%"}} />
    {devs.map(function(d,i){return <div key={"d"+i} style={{...lb,left:0,top:(11+i*23)+"%",transform:"translateY(-50%)"}}>{d}</div>})}
    <div style={{position:"absolute",left:"50%",top:"50%",transform:"translate(-50%,-50%)",width:130,height:170,borderRadius:14,border:"1.5px solid "+T+"40",background:B2,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:7,zIndex:3,boxShadow:"0 0 50px "+T+"10"}}>
      <div style={{fontSize:14,fontWeight:700,color:T,letterSpacing:1}}>EDGE AI BOX</div>
      <div style={{fontSize:10,color:DM}}>100 TOPS &middot; &lt;100ms</div>
      {[{l:"HAL",c:T},{l:"AI Engine",c:BL},{l:"Decisioning",c:V}].map(function(la,i){return <div key={i} style={{padding:"4px 12px",borderRadius:5,border:"1px solid "+la.c+"35",background:la.c+"10",fontSize:11,fontWeight:600,color:la.c}}>{la.l}</div>})}
    </div>
    {outs.map(function(o,i){return <div key={"o"+i} style={{...lb,right:0,top:(11+i*23)+"%",transform:"translateY(-50%)",color:o.c,border:"1px solid "+o.c+"25"}}>{o.l}</div>})}
  </div>);
}

function BoxSchematic(){
  var layers=[{n:"System-Wide Learning",sub:"The moat — observes all outcomes, compounds fleet-wide, OTA to every device",c:AM},{n:"Integrations",sub:"B2B dashboards · B2C app · OEM white-label · Partner APIs",c:PK},{n:"Contextual Decisioning",sub:"Learns routines · Baselines · 3 AM person ≠ 3 PM person",c:V},{n:"Edge AI Engine",sub:"YOLOv8 · EfficientNet · INT8 quantised · <100ms · <2W",c:BL},{n:"HAL",sub:"Single API across multiple ARM and x86 SoC families. New hardware becomes a supply decision, not an engineering rewrite.",c:T}];
  var al=useState(null),a=al[0],pp=useState(0);
  useEffect(function(){var id=setInterval(function(){pp[1](function(v){return(v+1)%5})},900);return function(){clearInterval(id)}},[]);
  return (<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:40,alignItems:"start"}}>
    <div><div style={{background:B2,border:"2px solid "+T+"35",borderRadius:20,overflow:"hidden",boxShadow:"0 0 80px "+T+"0C,0 20px 60px rgba(0,0,0,.4)"}}>
      <div style={{background:"linear-gradient(180deg,"+T+"12,transparent)",padding:"24px 24px 16px",borderBottom:"1px solid "+BD}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontSize:18,fontWeight:700,color:T,letterSpacing:1.5}}>EDGE AI BOX</div><div style={{fontSize:12,color:DM,marginTop:2}}>Sevyn8 Platform Device</div></div><div style={{display:"flex",gap:4}}>{[T,BL,V].map(function(c,i){return <div key={i} style={{width:8,height:8,borderRadius:"50%",background:c,opacity:pp[0]===i?1:.25,transition:"opacity .4s",boxShadow:pp[0]===i?"0 0 8px "+c:"none"}} />})}</div></div></div>
      <div style={{padding:"16px 20px"}}>{layers.map(function(la,i){var isA=pp[0]===i;return <div key={i} style={{display:"flex",alignItems:"center",gap:10,padding:"8px 12px",marginBottom:4,borderRadius:8,background:isA?la.c+"12":"transparent",borderLeft:"3px solid "+(isA?la.c:la.c+"30"),transition:"all .4s"}}><div style={{width:6,height:6,borderRadius:"50%",background:la.c,boxShadow:isA?"0 0 8px "+la.c:"none"}} /><span style={{fontSize:13,fontWeight:isA?600:500,color:isA?la.c:DM}}>{la.n}</span>{isA&&<div style={{marginLeft:"auto",fontSize:10,color:la.c,fontWeight:600}}>ACTIVE</div>}</div>})}</div>
      <div style={{padding:"12px 20px 16px",borderTop:"1px solid "+BD,display:"flex",gap:20,justifyContent:"center"}}>{[{l:"100 TOPS",s:"AI Compute"},{l:"<100ms",s:"Latency"},{l:"<2W",s:"Power"},{l:"Offline",s:"Mode"}].map(function(s,i){return <div key={i} style={{textAlign:"center"}}><div style={{fontSize:14,fontWeight:700,color:[T,BL,V,AM][i]}}>{s.l}</div><div style={{fontSize:9,color:DM,marginTop:1}}>{s.s}</div></div>})}</div>
      <div style={{padding:"0 20px 16px",display:"flex",gap:6,justifyContent:"center"}}>{["WiFi 6","LTE","BLE 5.4","Thread"].map(function(c){return <span key={c} style={{fontSize:10,padding:"3px 10px",borderRadius:4,border:"1px solid "+BD,color:DM}}>{c}</span>})}</div>
    </div><div style={{display:"flex",justifyContent:"center",gap:28,marginTop:16}}>{[{l:"PoE In",c:T},{l:"USB 3.0",c:BL},{l:"HDMI",c:V}].map(function(port,i){return <div key={i} style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:10,height:10,borderRadius:2,border:"1.5px solid "+port.c,background:port.c+"15"}} /><span style={{fontSize:11,color:DM}}>{port.l}</span></div>})}</div></div>
    <div style={{display:"flex",flexDirection:"column",gap:8}}><div style={{fontSize:11,textTransform:"uppercase",letterSpacing:3,color:DM,marginBottom:4,fontWeight:500}}>Platform layers</div>{layers.map(function(la,i){var active=a===i;return <div key={i} onClick={function(){al[1](active?null:i)}} style={{padding:"14px 18px",borderRadius:10,background:active?BG:B3,border:"1.5px solid "+(active?la.c+"55":BD),borderLeft:"4px solid "+la.c,cursor:"pointer",transition:"all .3s"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:15,fontWeight:600,color:active?TX:MT}}>{la.n}</span><span style={{fontSize:18,color:la.c,transition:"transform .3s",transform:active?"rotate(45deg)":"none",lineHeight:1}}>+</span></div>{active&&<p style={{fontSize:14,color:MT,lineHeight:1.7,marginTop:10}}>{la.sub}</p>}</div>})}</div>
  </div>);
}

function Pipe(){var s2=useState(0),st=s2[0];useEffect(function(){var id=setInterval(function(){s2[1](function(s){return(s+1)%5})},2400);return function(){clearInterval(id)}},[]);
  var S=[{l:"Raw feed",c:DM,d:"4K video from IP camera, thermal sensor, or IoT device enters the Edge AI Box."},{l:"HAL",c:T,d:"Hardware Abstraction Layer normalises across multiple ARM and x86 SoC families. SoC-agnostic by design."},{l:"AI Engine",c:BL,d:"YOLOv8 + EfficientNet INT8 on-device. Under 100ms, under 2W. Fully offline."},{l:"Decisioning",c:V,d:"Context engine applies learned routines. A person at 3 AM differs from 3 PM."},{l:"Action",c:AM,d:"Alert sent. Compliance logged. Dashboard updated. OTA improvement queued fleet-wide."}];
  return (<div><div style={{display:"flex",alignItems:"center",marginBottom:22}}>{S.map(function(s,i){return <div key={i} style={{flex:1,display:"flex",alignItems:"center",cursor:"pointer"}} onClick={function(){s2[1](i)}}><div style={{flex:"0 0 auto",width:80,padding:"12px 0",borderRadius:8,background:st===i?s.c+"15":"transparent",border:"1.5px solid "+(st>=i?s.c+"55":BD),textAlign:"center",transition:"all .4s",boxShadow:st===i?"0 0 16px "+s.c+"22":"none"}}><div style={{width:8,height:8,borderRadius:"50%",margin:"0 auto 6px",background:st>=i?s.c:DM,boxShadow:st===i?"0 0 12px "+s.c:"none"}} /><div style={{fontSize:11,fontWeight:600,color:st>=i?TX:DM}}>{s.l}</div></div>{i<4&&<div style={{flex:1,height:2,position:"relative",margin:"0 -1px"}}><div style={{position:"absolute",inset:0,background:BD}} /><div style={{position:"absolute",top:0,left:0,height:"100%",width:st>i?"100%":st===i?"50%":"0%",background:"linear-gradient(90deg,"+S[i].c+","+S[Math.min(i+1,4)].c+")",transition:"width .5s"}} /></div>}</div>})}</div><div style={{background:B2,border:"1px solid "+S[st].c+"25",borderRadius:10,padding:"20px 24px",borderLeft:"3px solid "+S[st].c}}><div style={{fontSize:16,fontWeight:600,color:S[st].c,marginBottom:6}}>{S[st].l}</div><div style={{fontSize:16,color:MT,lineHeight:1.75}}>{S[st].d}</div></div></div>)}

function Ctx(){var s2=useState(0),sc=s2[0];useEffect(function(){var id=setInterval(function(){s2[1](function(s){return(s+1)%6})},3000);return function(){clearInterval(id)}},[]);
  var S=[{t:"Person at door — 3:17 AM",x:"Unknown face · Unusual hour",dc:"⚠ Alert homeowner",c:AM},{t:"Door open + motion + face match",x:"Known delivery · Package expected · Camera + door + IoT",dc:"✓ Log silently, no alert",c:T},{t:"Person near shelf 4+ min",x:"Repeated reach · No basket",dc:"⚠ Concealment alert",c:PK},{t:"Cold room: temp rising + door open 4 min",x:"Thermal + door sensor + no pick order",dc:"⚠ Breach in 15 min — alert ops",c:V},{t:"Driver eyes closed 3+ sec",x:"Highway · Night shift · 6 hrs in",dc:"⚠ In-cab alert + fleet",c:AM},{t:"Forklift + BLE beacon + no hard hat",x:"Camera + proximity sensor + PPE check fused",dc:"⚠ Zone violation + PPE alert",c:PK}],s=S[sc];
  return (<div style={{maxWidth:600}}><div style={{display:"flex",gap:4,marginBottom:18}}>{S.map(function(z,i){return <div key={i} onClick={function(){s2[1](i)}} style={{flex:1,height:4,borderRadius:2,cursor:"pointer",background:i===sc?s.c:BD}} />})}</div>{[{l:"Detection",v:s.t},{l:"Context",v:s.x},{l:"Decision",v:s.dc}].map(function(r,i){return <div key={sc+"-"+i} style={{display:"flex",gap:18,alignItems:"center",padding:"16px 22px",marginBottom:6,background:i===2?s.c+"0D":B2,border:"1.5px solid "+(i===2?s.c+"44":BD),borderRadius:10}}><div style={{fontSize:11,textTransform:"uppercase",letterSpacing:1.5,color:DM,minWidth:68,fontWeight:600}}>{r.l}</div><div style={{width:1,height:20,background:BD}} /><div style={{fontSize:16,color:i===0?MT:s.c,fontWeight:i===2?600:400}}>{r.v}</div></div>})}</div>)}

function Fleet(){var p2=useState(-1),p=p2[0];useEffect(function(){var id=setInterval(function(){p2[1](function(v){return(v+1)%6})},1000);return function(){clearInterval(id)}},[]);
  var N=[{x:18,y:8,l:"Retail #1"},{x:52,y:3,l:"Retail #2"},{x:84,y:10,l:"Cold Store"},{x:10,y:82,l:"Fleet Hub"},{x:50,y:94,l:"Home"},{x:88,y:80,l:"Warehouse"}];
  return (<div style={{position:"relative",height:300,maxWidth:560}}><div style={{position:"absolute",left:"50%",top:"50%",transform:"translate(-50%,-50%)",width:90,height:90,borderRadius:"50%",background:"radial-gradient(circle,"+T+"1A,transparent)",border:"1.5px solid "+T+"40",display:"flex",alignItems:"center",justifyContent:"center",flexDirection:"column",zIndex:2,boxShadow:"0 0 40px "+T+"14"}}><div style={{fontSize:13,fontWeight:700,color:T}}>OTA</div><div style={{fontSize:10,color:MT}}>Fleet update</div></div>{N.map(function(n,i){return <div key={i}><svg style={{position:"absolute",inset:0,width:"100%",height:"100%",pointerEvents:"none"}}><line x1={n.x+"%"} y1={n.y+"%"} x2="50%" y2="50%" stroke={i<=p?T:BD} strokeWidth={i===p?1.5:.5} strokeDasharray={i<=p?"none":"4 7"} style={{transition:"all .5s"}} /></svg><div style={{position:"absolute",left:n.x+"%",top:n.y+"%",transform:"translate(-50%,-50%)",padding:"8px 16px",borderRadius:8,background:i===p?T+"1A":B3,border:"1.5px solid "+(i<=p?T+"50":BD),fontSize:14,fontWeight:500,color:i<=p?T:DM,transition:"all .5s",whiteSpace:"nowrap",zIndex:1}}>{n.l}{i<=p?" ✓":""}</div></div>})}</div>)}

function Outcomes(p){
  var items=[
    {v:"Retail",ic:"◆",c:T,id:"retail",before:"600 cameras, ESL tags, and RFID readers across 40 stores. None of them talk to each other. Shrinkage costs ₹4,200 Cr annually.",after:"40-60% shrinkage reduction",metric:"₹4,200Cr",ml:"saved annually",detail:"Deploy new intelligent cameras or connect your existing CCTV — either way, camera + ESL + RFID fuse on one platform. Concealment detected in real time."},
    {v:"Smart Home",ic:"□",c:BL,id:"home",before:"Camera alerts for motion. Door sensor alerts for opens. Smoke detector alerts. 90 notifications a day. None of them understand context.",after:"3-5 decisions that matter",metric:"97%",ml:"noise eliminated",detail:"The Sevyn8 Hub connects your existing devices. Or deploy new smart sensors with AI built in. Either way — one intelligence layer, no cloud."},
    {v:"Cold Storage",ic:"○",c:V,id:"coldchain",before:"Temperature loggers beep after the damage. Thermal cameras exist but nobody correlates them with humidity, door sensors, or compliance data.",after:"Predicted 30 min early",metric:"40-60%",ml:"losses prevented",detail:"Deploy new thermal-AI cameras or connect existing sensors — all fused on one device. FSSAI automated end-to-end."},
    {v:"Fleet",ic:"▲",c:AM,id:"fleet",before:"GPS tracks location. Dashcams record but nobody watches. Vibration sensors log data to a separate system. Nothing is connected.",after:"Compliance is continuous",metric:"60%",ml:"fewer incidents",detail:"Deploy AI dashcams with on-board inference or connect existing cameras and sensors via one box. One dashboard. Predictive, not reactive."}
  ];
  var s2=useState(0),active=s2[0],phase=useState("before"),ph=phase[0];
  useEffect(function(){
    var id=setInterval(function(){
      phase[1](function(p2){
        if(p2==="before") return "after";
        s2[1](function(a){return (a+1)%4});
        return "before";
      });
    },4000);
    return function(){clearInterval(id)};
  },[]);
  var it=items[active];
  return (<div>
    <div style={{display:"flex",gap:6,marginBottom:32,justifyContent:"center"}}>{items.map(function(item,i){return (
      <div key={i} onClick={function(){s2[1](i);phase[1]("before")}} style={{display:"flex",alignItems:"center",gap:8,padding:"10px 20px",borderRadius:8,cursor:"pointer",background:active===i?item.c+"12":"transparent",border:"1.5px solid "+(active===i?item.c+"44":BD),transition:"all .4s"}}>
        <span style={{fontSize:14,color:item.c}}>{item.ic}</span>
        <span style={{fontSize:14,fontWeight:active===i?600:500,color:active===i?TX:DM,transition:"color .3s"}}>{item.v}</span>
      </div>
    )})}</div>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:24,minHeight:200}}>
      <div style={{position:"relative",overflow:"hidden"}}>
        <div style={{opacity:ph==="before"?1:.5,transform:ph==="before"?"translateY(0)":"translateY(-8px)",transition:"all .6s cubic-bezier(.22,1,.36,1)",padding:32,borderRadius:14,border:"1.5px solid "+(ph==="before"?"rgba(140,160,200,.15)":BD),background:ph==="before"?B3:BG,height:"100%",display:"flex",flexDirection:"column",justifyContent:"center"}}>
          <div style={{fontSize:11,textTransform:"uppercase",letterSpacing:2,color:PK,marginBottom:12,fontWeight:600}}>Without Sevyn8</div>
          <p style={{fontSize:19,color:ph==="before"?TX:MT,lineHeight:1.7,transition:"color .4s"}}>{it.before}</p>
        </div>
      </div>
      <div style={{position:"relative",overflow:"hidden"}}>
        <div style={{opacity:ph==="after"?1:.15,transform:ph==="after"?"translateY(0)":"translateY(16px)",transition:"all .6s cubic-bezier(.22,1,.36,1) .15s",padding:32,borderRadius:14,border:"1.5px solid "+(ph==="after"?it.c+"55":BD),background:ph==="after"?it.c+"0A":BG,height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",boxShadow:ph==="after"?"0 0 40px "+it.c+"12":"none"}}>
          <div style={{fontSize:10,textTransform:"uppercase",letterSpacing:2,color:it.c,marginBottom:12,fontWeight:500}}>With Sevyn8</div>
          <div style={{display:"flex",alignItems:"baseline",gap:12,marginBottom:12}}><span style={{...hd,fontSize:36,fontWeight:800,color:TX}}>{it.after}</span></div>
          <p style={{fontSize:15,color:MT,lineHeight:1.7,marginBottom:16}}>{it.detail}</p>
          <div style={{display:"inline-flex",alignItems:"center",gap:8,cursor:"pointer",color:it.c,fontSize:13,fontWeight:600}} onClick={function(){p.go("sol-"+it.id)}}>See {it.v.toLowerCase()} solution <span>{"→"}</span></div>
        </div>
      </div>
    </div>
    <div style={{display:"flex",justifyContent:"center",gap:4,marginTop:24}}>{items.map(function(item,i){return <div key={i} style={{width:active===i?32:8,height:4,borderRadius:2,background:active===i?item.c:BD,transition:"all .4s"}} />})}</div>
  </div>);
}

function Home(p){
  var go=p.go,l2=useState(false),ld=l2[0];
  useEffect(function(){setTimeout(function(){l2[1](true)},150)},[]);
  return (<div>
    <section style={{minHeight:"100vh",display:"flex",alignItems:"center",padding:"100px 40px 60px",maxWidth:1200,margin:"0 auto"}}>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:60,alignItems:"center",width:"100%"}}>
        <div style={{opacity:ld?1:0,transform:ld?"none":"translateY(24px)",transition:"all 1s cubic-bezier(.16,1,.3,1) .3s"}}>
          <div style={{display:"inline-flex",alignItems:"center",gap:7,padding:"5px 14px",border:"1px solid "+T+"28",borderRadius:16,marginBottom:28}}><div style={{width:7,height:7,borderRadius:"50%",background:T,boxShadow:"0 0 10px "+T}} /><span style={{fontSize:13,color:T,fontWeight:500}}>AI at Edge Platform</span></div>
          <h1 style={{...hd,fontSize:52,lineHeight:1.06,fontWeight:700,marginBottom:18}}>Intelligence at the edge.</h1>
          <p style={{fontSize:18,color:TX,lineHeight:1.8,marginBottom:24,maxWidth:440}}>90 daily alerts become 3 genuine decisions. Shrinkage drops 40-60%. Cold chain breaches predicted 30 minutes early. Fleet incidents cut by 60%.</p>
          <p style={{fontSize:15,color:DM,lineHeight:1.75,marginBottom:32,maxWidth:420}}>Deploy new intelligent devices with AI built in — or make your existing infrastructure smarter with one box. Under 100ms. Fully offline. No cloud.</p>
          <div style={{display:"flex",gap:12}}><button style={bn} onClick={function(){go("contact")}}>Book a 60-day POC</button><button style={b2} onClick={function(){go("platform")}}>See the technology</button></div>
        </div>
        <div style={{position:"relative",height:480,opacity:ld?1:0,transition:"opacity 1.2s ease .6s"}}><HeroAnim /></div>
      </div>
    </section>

    <section style={{borderTop:"1px solid "+BD,background:B2}}><div style={{maxWidth:1100,margin:"0 auto",padding:"56px 40px"}}><Rv><div style={{textAlign:"center",marginBottom:40}}><Tg>What changes</Tg><h2 style={{...hd,fontSize:34,fontWeight:700}}>Before Sevyn8 vs. After</h2></div></Rv>
      <Outcomes go={go} />
    </div></section>

    <Sc bt><Rv><Tg>Two paths. One platform.</Tg><h2 style={{...hd,fontSize:34,fontWeight:700,marginBottom:10}}>New deployment or existing infrastructure. Same intelligence.</h2><p style={{fontSize:17,color:MT,marginBottom:40}}>Deploy purpose-built intelligent devices with AI on-board — or add a Sevyn8 box to the sensors you already have. Both paths run the same platform.</p></Rv>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:20,marginBottom:32}}>
        <Rv d={0}><div style={{padding:32,borderRadius:14,border:"1.5px solid "+T+"40",background:T+"06"}}>
          <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:16}}><div style={{width:40,height:40,borderRadius:8,background:T+"18",border:"1.5px solid "+T+"40",display:"flex",alignItems:"center",justifyContent:"center",fontSize:16,fontWeight:800,color:T}}>S8</div><div style={{fontSize:11,textTransform:"uppercase",letterSpacing:2,color:T,fontWeight:600}}>New deployment</div></div>
          <h3 style={{fontSize:20,fontWeight:700,marginBottom:10}}>Intelligent devices with AI built in</h3>
          <p style={{fontSize:15,color:MT,lineHeight:1.75,marginBottom:16}}>Purpose-built cameras, sensors, and gateways with on-board NPU. Sevyn8 platform embedded at factory. AI runs natively on the device — no separate box needed.</p>
          <div style={{display:"flex",flexWrap:"wrap",gap:6}}>{["On-board NPU/CPU","AI at the device","OEM white-label","Factory embedded"].map(function(t){return <span key={t} style={{fontSize:11,padding:"4px 10px",borderRadius:4,border:"1px solid "+T+"25",color:T,background:T+"08"}}>{t}</span>})}</div>
        </div></Rv>
        <Rv d={0.1}><div style={{padding:32,borderRadius:14,border:"1.5px solid "+AM+"40",background:AM+"06"}}>
          <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:16}}><div style={{width:40,height:40,borderRadius:8,background:AM+"18",border:"1.5px solid "+AM+"40",display:"flex",alignItems:"center",justifyContent:"center",fontSize:14,fontWeight:700,color:AM}}>Hub</div><div style={{fontSize:11,textTransform:"uppercase",letterSpacing:2,color:AM,fontWeight:600}}>Existing infrastructure</div></div>
          <h3 style={{fontSize:20,fontWeight:700,marginBottom:10}}>Make your dumb devices intelligent</h3>
          <p style={{fontSize:15,color:MT,lineHeight:1.75,marginBottom:16}}>Already have cameras, thermal sensors, IoT nodes, RFID readers installed? Add one Sevyn8 Hub or Edge AI Box to your network. It ingests feeds from every device and runs AI inference locally.</p>
          <div style={{display:"flex",flexWrap:"wrap",gap:6}}>{["Any existing device","One box per site","No rip-and-replace","60-day results"].map(function(t){return <span key={t} style={{fontSize:11,padding:"4px 10px",borderRadius:4,border:"1px solid "+AM+"25",color:AM,background:AM+"08"}}>{t}</span>})}</div>
        </div></Rv>
      </div>
      <Rv d={0.2}><div style={{textAlign:"center",padding:"24px 0",borderTop:"1px solid "+BD}}><p style={{fontSize:16,color:MT}}>Both paths converge on the same platform. Same AI engine. Same contextual decisioning. Same fleet-wide learning. Same dashboard.</p></div></Rv>
    </Sc>
    <Sc bg={B2} bt><Rv><Tg c={V}>The intelligence</Tg><h2 style={{...hd,fontSize:34,fontWeight:700,marginBottom:10}}>Devices generate data. Sevyn8 creates understanding.</h2><p style={{fontSize:17,color:MT,marginBottom:34}}>Whether AI runs on the device itself or on a Sevyn8 box nearby — camera feeds, thermal readings, IoT signals, and RFID events fuse into one context engine. Same event, different context, different decision.</p></Rv><Rv d={.12}><Ctx /></Rv></Sc>
    <Sc bt><Rv><Tg>Your industry</Tg><h2 style={{...hd,fontSize:34,fontWeight:700,marginBottom:12}}>Find your problem. See the outcome.</h2><p style={{fontSize:17,color:MT,marginBottom:40}}>Click into your industry. Fresh deployment or existing infrastructure — same outcomes.</p></Rv>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>
        {[{s:SOL[1],pain:"600 cameras, ESL tags, and RFID across 40 stores — and none of them talk to each other. LP reviews 5% of footage after the fact.",out:"40-60% shrinkage reduction. 98%+ footfall accuracy. 60-day POC.",c:T},
          {s:SOL[2],pain:"GPS, dashcams, vibration sensors, facility cameras — four systems, four dashboards, zero correlation.",out:"60% fewer incidents. Continuous compliance. Auditable from day one.",c:AM},
          {s:SOL[3],pain:"Thermal cameras, temperature probes, humidity sensors, door sensors — all logging separately. FSSAI audit prep takes weeks.",out:"Breaches predicted 30 min early. FSSAI automated. Audit prep: hours.",c:V},
          {s:SOL[0],pain:"Cameras, doorbells, motion sensors, smoke detectors — 90 alerts a day from devices that do not talk to each other.",out:"3-5 decisions that matter. Zero data to cloud. Works without WiFi.",c:BL}
        ].map(function(v,i){return <Rv key={i} d={i*.06}><div onClick={function(){go("sol-"+v.s.id)}} style={{padding:28,borderRadius:14,border:"1.5px solid "+BD,background:BG,cursor:"pointer",transition:"border-color .3s",borderLeft:"4px solid "+v.c}}>
          <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:16}}><span style={{fontSize:16,color:v.c}}>{v.s.ic}</span><span style={{fontSize:18,fontWeight:700}}>{v.s.n}</span></div>
          <p style={{fontSize:15,color:MT,lineHeight:1.7,marginBottom:16}}>{v.pain}</p>
          <div style={{padding:"14px 18px",borderRadius:8,background:v.c+"0A",border:"1px solid "+v.c+"22"}}>
            <div style={{fontSize:11,textTransform:"uppercase",letterSpacing:2,color:v.c,fontWeight:600,marginBottom:6}}>With Sevyn8</div>
            <p style={{fontSize:16,fontWeight:600,color:TX,lineHeight:1.5}}>{v.out}</p>
          </div>
          <div style={{marginTop:14,fontSize:13,color:v.c,fontWeight:600}}>See {v.s.n.toLowerCase()} solution {"→"}</div>
        </div></Rv>})}
      </div>
    </Sc>

    <section style={{borderTop:"1px solid "+BD,background:B2}}><div style={{maxWidth:1100,margin:"0 auto",padding:"40px",display:"flex",alignItems:"center",justifyContent:"center",gap:48,flexWrap:"wrap"}}><span style={{fontSize:12,textTransform:"uppercase",letterSpacing:2,color:DM}}>Deployed at</span>{["Global ESL Leader","Premium Fashion Retailer"].map(function(n,i){return <div key={i} style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:8,height:8,borderRadius:"50%",background:AM}} /><span style={{fontSize:14,fontWeight:600,color:MT}}>{n}</span></div>})}</div></section>

    <Sc><Rv><div style={{textAlign:"center"}}><h2 style={{...hd,fontSize:34,fontWeight:700,marginBottom:14}}>New devices or existing infrastructure. See it work in 60 days.</h2><p style={{fontSize:17,color:MT,marginBottom:30,maxWidth:480,margin:"0 auto 30px"}}>Deploy purpose-built intelligent devices or make your existing infrastructure smarter. Same platform, same AI, same results. 60-day POC.</p><div style={{display:"flex",gap:12,justifyContent:"center"}}><button style={bn} onClick={function(){go("contact")}}>Book a 60-day POC</button><button style={b2} onClick={function(){go("platform")}}>See the technology</button></div></div></Rv></Sc>
  </div>)}

function PlatPg(p){return <div style={{paddingTop:80}}><Sc><Rv><Tg>Platform</Tg><h1 style={{...hd,fontSize:46,fontWeight:700,marginBottom:18}}>Six layers. One intelligence substrate.</h1><p style={{fontSize:18,color:MT,lineHeight:1.8,maxWidth:500}}>System-Wide Learning at the apex. Compounding intelligence pushed to every device via OTA.</p></Rv></Sc><Sc bg={B2} bt><Rv><h2 style={{...hd,fontSize:32,fontWeight:700,marginBottom:30}}>Inference pipeline</h2></Rv><Rv d={.1}><Pipe /></Rv></Sc><Sc><Rv><h2 style={{...hd,fontSize:32,fontWeight:700,marginBottom:30}}>Contextual decisioning</h2></Rv><Rv d={.1}><Ctx /></Rv></Sc><Sc bg={B2} bt><Rv><h2 style={{...hd,fontSize:32,fontWeight:700,marginBottom:30}}>Fleet intelligence</h2></Rv><Rv d={.1}><Fleet /></Rv></Sc><Sc bt><Rv><div style={{textAlign:"center"}}><button style={bn} onClick={function(){p.go("box")}}>Edge AI Box {"→"}</button></div></Rv></Sc></div>}

function BoxPg(p){return <div style={{paddingTop:80}}><Sc><Rv><Tg c={BL}>Product</Tg><h1 style={{...hd,fontSize:46,fontWeight:700,marginBottom:18}}>Edge AI Box</h1><p style={{fontSize:18,color:MT,lineHeight:1.8,maxWidth:540}}>The entire Sevyn8 platform in one device. Any camera. Any SoC. Four industries.</p></Rv></Sc><Sc bg={B2} bt><Rv><BoxSchematic /></Rv></Sc><Sc><Rv><h3 style={{fontSize:11,textTransform:"uppercase",letterSpacing:3,color:DM,marginBottom:14}}>Connects to</h3><p style={{fontSize:16,color:MT,lineHeight:1.85}}>Fixed Box IP Camera &middot; Dome Camera &middot; Bullet Camera &middot; PTZ Camera &middot; Fisheye Panoramic &middot; Thermal LWIR &middot; ANPR Camera &middot; In-Cab IR Camera &middot; Shelf-Edge Camera &middot; WiFi Consumer Camera &middot; Video Doorbell &middot; IoT Sensor Nodes &middot; BLE Beacons &middot; RFID Readers</p></Rv></Sc><Sc bg={B2} bt><Rv><h3 style={{fontSize:11,textTransform:"uppercase",letterSpacing:3,color:DM,marginBottom:22}}>Specifications</h3></Rv><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(200px,1fr))",gap:10}}>{[{k:"AI compute",v:"Up to 100 TOPS"},{k:"Inference",v:"Under 100ms"},{k:"Power",v:"Under 2 watts"},{k:"Connectivity",v:"WiFi 6, LTE, BLE 5.4, Thread"},{k:"SoC",v:"ARM & x86 families supported"},{k:"Security",v:"STQC ER-1 through ER-5"},{k:"Compliance",v:"BIS CRS, DPDP, HIPAA"},{k:"Updates",v:"Encrypted OTA fleet-wide"}].map(function(s,i){return <Rv key={i} d={i*.04}><div style={{padding:"18px 20px",borderRadius:8,border:"1px solid "+BD,background:BG}}><div style={{fontSize:11,color:DM,textTransform:"uppercase",letterSpacing:1,marginBottom:5}}>{s.k}</div><div style={{fontSize:16,fontWeight:500}}>{s.v}</div></div></Rv>})}</div></Sc><Sc bt><Rv><div style={{textAlign:"center"}}><button style={bn} onClick={function(){p.go("contact")}}>Request evaluation unit</button></div></Rv></Sc></div>}

function SolPg(p){var s=p.s,sc2=useState(0),sci=sc2[0];
  useEffect(function(){if(!s.scn)return;var id=setInterval(function(){sc2[1](function(v){return(v+1)%s.scn.length})},6000);return function(){clearInterval(id)}},[s.scn]);
  return <div style={{paddingTop:80}}>
  <Sc><Rv><div style={{fontSize:14,color:MT,marginBottom:16}}><span style={{color:T,cursor:"pointer"}} onClick={function(){p.go("home")}}>Solutions</span> / {s.n}</div><h1 style={{...hd,fontSize:44,fontWeight:700,lineHeight:1.08,maxWidth:640,marginBottom:22}}>{s.h}</h1><p style={{fontSize:18,color:MT,lineHeight:1.85,maxWidth:580}}>{s.d}</p></Rv></Sc>
  {s.st&&<section style={{borderTop:"1px solid "+BD,background:B2}}><div style={{maxWidth:960,margin:"0 auto",padding:"40px",display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14}}>{s.st.map(function(st,i){return <Rv key={i} d={i*.08}><div style={{padding:20,borderRadius:10,border:"1px solid "+BD,background:BG,textAlign:"center"}}><div style={{fontSize:28,fontWeight:700,...hd,color:T}}>{st.v}</div><div style={{fontSize:13,color:MT,marginTop:5}}>{st.l}</div></div></Rv>})}</div></section>}

  {s.scn&&<Sc bt><Rv><Tg c={AM}>A day without vs. with</Tg><h2 style={{...hd,fontSize:32,fontWeight:700,marginBottom:28}}>Same moment. Different outcome.</h2></Rv>
    <div style={{display:"flex",gap:6,marginBottom:24}}>{s.scn.map(function(sc,i){return <div key={i} onClick={function(){sc2[1](i)}} style={{padding:"8px 16px",borderRadius:6,cursor:"pointer",background:sci===i?AM+"15":"transparent",border:"1px solid "+(sci===i?AM+"44":BD),fontSize:13,fontWeight:sci===i?600:500,color:sci===i?AM:DM,transition:"all .3s"}}>{sc.t}</div>})}</div>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:20}}>
      <Rv d={0}><div style={{padding:28,borderRadius:14,border:"1.5px solid "+PK+"30",background:PK+"06",height:"100%"}}>
        <div style={{fontSize:11,textTransform:"uppercase",letterSpacing:2,color:PK,marginBottom:14,fontWeight:600}}>Without Sevyn8</div>
        <div style={{fontSize:13,color:DM,marginBottom:10,fontFamily:"monospace"}}>{s.scn[sci].t}</div>
        <p style={{fontSize:17,color:TX,lineHeight:1.75}}>{s.scn[sci].b}</p>
      </div></Rv>
      <Rv d={0.1}><div style={{padding:28,borderRadius:14,border:"1.5px solid "+T+"40",background:T+"06",height:"100%",boxShadow:"0 0 30px "+T+"08"}}>
        <div style={{fontSize:11,textTransform:"uppercase",letterSpacing:2,color:T,marginBottom:14,fontWeight:600}}>With Sevyn8</div>
        <div style={{fontSize:13,color:DM,marginBottom:10,fontFamily:"monospace"}}>{s.scn[sci].t}</div>
        <p style={{fontSize:17,color:TX,lineHeight:1.75}}>{s.scn[sci].w}</p>
      </div></Rv>
    </div>
    <div style={{display:"flex",justifyContent:"center",gap:4,marginTop:20}}>{s.scn.map(function(sc,i){return <div key={i} style={{width:sci===i?28:8,height:4,borderRadius:2,background:sci===i?AM:BD,transition:"all .4s"}} />})}</div>
  </Sc>}

  {s.sens&&<Sc bg={B2} bt><Rv><Tg>Sensor ecosystem</Tg><h2 style={{...hd,fontSize:32,fontWeight:700,marginBottom:12}}>What feeds into the platform</h2><p style={{fontSize:16,color:MT,marginBottom:28}}>Every device below connects to one Sevyn8 box — or runs Sevyn8 AI natively on-board.</p></Rv>
    <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10}}>{s.sens.map(function(sn,i){return <Rv key={i} d={i*.05}><div style={{padding:"16px 20px",borderRadius:10,border:"1px solid "+BD,background:BG,display:"flex",alignItems:"center",gap:12}}><div style={{width:8,height:8,borderRadius:"50%",background:T,flexShrink:0}} /><span style={{fontSize:15,fontWeight:500}}>{sn}</span></div></Rv>})}</div>
  </Sc>}

  {s.wf&&<Sc bt><Rv><h3 style={{fontSize:11,textTransform:"uppercase",letterSpacing:3,color:PK,marginBottom:12}}>What you are stuck with today</h3><p style={{fontSize:16,color:MT,lineHeight:1.85,maxWidth:620}}>{s.wf}</p></Rv></Sc>}
  <Sc bg={B2} bt><Rv><h3 style={{fontSize:11,textTransform:"uppercase",letterSpacing:3,color:T,marginBottom:22}}>What changes with Sevyn8</h3></Rv>{s.cs.map(function(c,i){var pts=c.split(" \u2014 ");return <Rv key={i} d={i*.05}><div style={{display:"flex",gap:16,padding:"18px 0",borderBottom:"1px solid "+BD}}><div style={{width:6,height:6,borderRadius:"50%",background:T,marginTop:9,flexShrink:0}} /><div><span style={{fontSize:16,fontWeight:600,color:TX}}>{pts[0]}</span>{pts[1]&&<span style={{fontSize:16,color:MT}}> &mdash; {pts[1]}</span>}</div></div></Rv>})}</Sc>

  <Sc bt><Rv><Tg>Two deployment paths</Tg><h2 style={{...hd,fontSize:32,fontWeight:700,marginBottom:28}}>New intelligent devices or existing infrastructure.</h2></Rv>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginBottom:24}}>
      <Rv d={0}><div style={{padding:24,borderRadius:12,border:"1.5px solid "+T+"35",background:T+"05"}}>
        <div style={{fontSize:11,textTransform:"uppercase",letterSpacing:2,color:T,marginBottom:10,fontWeight:600}}>Greenfield</div>
        <h4 style={{fontSize:17,fontWeight:600,marginBottom:8}}>Deploy new devices with AI built in</h4>
        <p style={{fontSize:14,color:MT,lineHeight:1.7}}>Purpose-built devices with on-board NPU running the Sevyn8 platform natively. No separate box needed. AI inference happens on the device itself.</p>
      </div></Rv>
      <Rv d={0.08}><div style={{padding:24,borderRadius:12,border:"1.5px solid "+AM+"35",background:AM+"05"}}>
        <div style={{fontSize:11,textTransform:"uppercase",letterSpacing:2,color:AM,marginBottom:10,fontWeight:600}}>Brownfield</div>
        <h4 style={{fontSize:17,fontWeight:600,marginBottom:8}}>Add intelligence to what you have</h4>
        <p style={{fontSize:14,color:MT,lineHeight:1.7}}>Connect your existing cameras, sensors, and IoT devices to one Sevyn8 Hub or Edge AI Box. It ingests all feeds and runs AI inference locally.</p>
      </div></Rv>
    </div>
  </Sc>

  <Sc bg={B2} bt><Rv><h3 style={{fontSize:11,textTransform:"uppercase",letterSpacing:3,color:DM,marginBottom:26}}>Your path to results</h3></Rv><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:14}}>{["Start","Scale","Compound"].map(function(l,i){return <Rv key={i} d={i*.1}><div style={{padding:24,borderRadius:12,border:"1px solid "+BD,background:BG}}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:12}}><div style={{width:28,height:28,borderRadius:"50%",background:T+"15",border:"1.5px solid "+T+"40",display:"flex",alignItems:"center",justifyContent:"center",fontSize:13,fontWeight:700,color:T}}>{i+1}</div><span style={{fontSize:12,textTransform:"uppercase",letterSpacing:2,color:T,fontWeight:600}}>{l}</span></div><p style={{fontSize:15,color:MT,lineHeight:1.75}}>{s.dp[i]}</p></div></Rv>})}</div></Sc>
  <Sc bt><Rv><div style={{textAlign:"center"}}><h2 style={{...hd,fontSize:28,fontWeight:700,marginBottom:14}}>Ready to see it work?</h2><p style={{fontSize:16,color:MT,marginBottom:24}}>60-day POC. New devices or existing infrastructure. Measurable results.</p><button style={bn} onClick={function(){p.go("contact")}}>Start the conversation {"→"}</button></div></Rv></Sc></div>}

function PartPg(p){var cats=[{t:"Silicon Partners (ARM & x86)",i:[["Tier-1 Mobile SoC Provider","Leading ARM-based application processor with dedicated NPU delivering up to 8 TOPS. WiFi 6E integrated. Primary SoC for the Edge AI Box. Design Partnership Agreement signed.","ARM SoC"],["Vision-Grade SoC Provider","4 TOPS dedicated vision processor with 4K ISP. Camera-optimised silicon. STQC ER-5 certified, US-origin. Ideal for surveillance and smart city deployments.","ARM SoC"],["Low-Power IoT SoC Provider","LTE-M/NB-IoT cellular SoC for IoT gateways and BLE 5.4 SoC for ESL and sensor mesh networks. Ultra-low power for battery-operated edge nodes.","IoT SoC"]]},{t:"Security Silicon",i:[["Hardware Security Partner","TPM 2.0 for hardware root of trust. Dedicated secure element for device identity provisioning at scale. Secure MCU for isolated cryptographic operations. DPA signed.","Security"]]},{t:"Sensor & Module Partners",i:[["Global Image Sensor Leader","Industry-leading image sensor family for camera modules. High dynamic range and low-light performance optimised specifically for on-device edge AI inference.","Sensor"],["Pre-Certified Module Provider","Pre-certified LTE Cat1bis, WiFi 6, and secure MCU modules with WPC ETA certification. Saves each OEM partner significant per-SKU compliance cost and time.","Module"],["WiFi 6E Module Specialist","Pre-certified WiFi 6E modules for camera and gateway integration. Regulatory approvals included, accelerating OEM time-to-market.","Module"]]},{t:"Design Partners",i:[["Concept-to-product design","Industrial design, mechanical engineering, thermal management, and design-for-manufacturing for Edge AI Box and Hub hardware.","Design"],["System integration","Full AI-at-Edge stack deployment combining vision, IoT sensors, and edge compute into unified customer solutions.","Integration"]]}];
  return <div style={{paddingTop:80}}><Sc><Rv><Tg>Partners</Tg><h1 style={{...hd,fontSize:44,fontWeight:700,marginBottom:18,maxWidth:500}}>Technology partners. Intelligence infrastructure.</h1><p style={{fontSize:18,color:MT,lineHeight:1.8,maxWidth:540}}>Sevyn8 partners with world-class silicon, sensor, and design firms to build the most capable edge AI platform on the market. We work with the largest ARM and x86 SoC providers, leading global and niche sensor companies, and specialist design houses.</p></Rv></Sc>
    <Sc bg={B2} bt><Rv><h3 style={{fontSize:11,textTransform:"uppercase",letterSpacing:3,color:DM,marginBottom:22}}>OEM licensing model</h3></Rv><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}>{[["01","Embed","Sevyn8 platform — HAL, firmware, AI models, decisioning — integrates into your hardware at factory level"],["02","Ship","Your brand, your distribution, your customers. The intelligence inside is Sevyn8 — invisible platform, visible value"],["03","Monetise","One-time hardware sale becomes recurring SaaS revenue. Cloud AI upsell converts device buyers into subscribers"],["04","Compound","Fleet learning improves every device you ship. Your 100,000th unit outperforms your competitor's latest launch"]].map(function(s,i){return <Rv key={i} d={i*.08}><div style={{padding:22,borderRadius:10,border:"1px solid "+BD,background:BG}}><span style={{fontFamily:"monospace",fontSize:13,color:T}}>{s[0]}</span><h4 style={{fontSize:17,fontWeight:600,margin:"8px 0 5px"}}>{s[1]}</h4><p style={{fontSize:14,color:MT,lineHeight:1.7}}>{s[2]}</p></div></Rv>})}</div></Sc>
    {cats.map(function(cat,ci){return <Sc key={ci} bg={ci%2===0?undefined:B2} bt><Rv><h3 style={{fontSize:11,textTransform:"uppercase",letterSpacing:3,color:DM,marginBottom:22}}>{cat.t}</h3></Rv><div style={{display:"grid",gridTemplateColumns:cat.i.length>1?"1fr 1fr":"1fr",gap:12}}>{cat.i.map(function(q,j){return <Rv key={j} d={j*.06}><div style={{padding:22,borderRadius:10,border:"1px solid "+BD,background:ci%2===0?B2:BG}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><span style={{fontSize:17,fontWeight:700}}>{q[0]}</span><span style={{fontSize:11,color:T,padding:"4px 12px",border:"1px solid "+T+"25",borderRadius:5}}>{q[2]}</span></div><p style={{fontSize:15,color:MT,lineHeight:1.7}}>{q[1]}</p></div></Rv>})}</div></Sc>})}
    <Sc bg={B2} bt><Rv><h3 style={{fontSize:11,textTransform:"uppercase",letterSpacing:3,color:DM,marginBottom:22}}>Current customers</h3><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14}}><Rv d={0}><div style={{padding:24,borderRadius:12,border:"1px solid "+BD,background:BG}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10}}><span style={{fontSize:18,fontWeight:700}}>Global ESL Leader</span><span style={{fontSize:10,color:AM,padding:"3px 10px",border:"1px solid "+AM+"25",borderRadius:4,fontWeight:500}}>Enterprise</span></div><p style={{fontSize:15,color:MT,lineHeight:1.75}}>One of the world's largest Electronic Shelf Label companies. Sevyn8 platform deployed across their AI-at-Edge retail infrastructure combining ESL, RFID, and camera intelligence into a unified solution.</p></div></Rv><Rv d={0.08}><div style={{padding:24,borderRadius:12,border:"1px solid "+BD,background:BG}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10}}><span style={{fontSize:18,fontWeight:700}}>Premium Fashion Retailer</span><span style={{fontSize:10,color:AM,padding:"3px 10px",border:"1px solid "+AM+"25",borderRadius:4,fontWeight:500}}>Enterprise</span></div><p style={{fontSize:15,color:MT,lineHeight:1.75}}>A global-scale premium fashion retail brand. Sevyn8 powers in-store analytics including footfall, conversion tracking, and loss prevention across their retail network.</p></div></Rv></div></Rv></Sc>
    <Sc bt><Rv><div style={{textAlign:"center"}}><button style={bn} onClick={function(){p.go("contact")}}>Become a partner {"→"}</button></div></Rv></Sc></div>}

function AboutPg(){return <div style={{paddingTop:80}}>
  <Sc><Rv><Tg>Our Story</Tg><h1 style={{...hd,fontSize:46,fontWeight:700,lineHeight:1.06,marginBottom:22,maxWidth:560}}>Seven layers of intelligence. The eighth is infinity.</h1><p style={{fontSize:18,color:MT,lineHeight:1.85,maxWidth:560}}>The name encodes the thesis. Seven capabilities no single competitor holds. An eighth element &mdash; system-wide learning &mdash; that ensures the gap only widens.</p></Rv></Sc>

  <Sc bg={B2} bt><Rv><Tg c={T}>The sevyn</Tg><h2 style={{...hd,fontSize:34,fontWeight:700,marginBottom:20}}>The full stack. All seven.</h2></Rv>
    <Rv d={0.1}><p style={{fontSize:17,color:MT,lineHeight:1.85,marginBottom:20,maxWidth:640}}>Edge AI requires seven capabilities simultaneously: SoC access, firmware and HAL, AI/ML models, manufacturing, supply chain, go-to-market, and ecosystem. Chip companies own silicon but can't build products. ODMs manufacture but can't write AI. Software startups have models but no hardware DNA. No other company in Indian edge AI holds all seven. Sevyn8 does.</p></Rv>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(125px,1fr))",gap:8}}>{["SoC access","Firmware + HAL","AI/ML models","Manufacturing","Supply chain","Go-to-market","Ecosystem"].map(function(f,i){return <Rv key={i} d={.05+i*.04}><div style={{padding:14,borderRadius:7,border:"1px solid "+T+"25",background:T+"08",textAlign:"center",fontSize:14,fontWeight:500,color:T}}>{f}</div></Rv>})}</div>
  </Sc>

  <Sc bt><Rv><Tg c={AM}>The origin</Tg><h2 style={{...hd,fontSize:34,fontWeight:700,marginBottom:20}}>Forged at Motorola.</h2></Rv>
    <Rv d={0.1}><p style={{fontSize:17,color:MT,lineHeight:1.85,marginBottom:18,maxWidth:640}}>The conviction that you need all seven didn't come from a whiteboard. It came from scars. The founding team met in the Motorola trenches &mdash; building Motorola India into the number two mobile brand. That era was a masterclass in full-stack ownership: hardware, software, supply chain, GTM, and ecosystem held together.</p></Rv>
    <Rv d={0.15}><p style={{fontSize:17,color:MT,lineHeight:1.85,maxWidth:640}}>They also watched what happened when the stack fragmented. When brilliant technology died in the gap between "it works in the lab" and "it ships at scale." That experience became the founding DNA. You cannot half-build an edge platform. You either hold all seven, or you're building on someone else's foundation.</p></Rv>
  </Sc>

  <Sc bg={B2} bt><Rv><Tg c={AM}>The eight</Tg><h2 style={{...hd,fontSize:34,fontWeight:700,marginBottom:20}}>The compounding layer.</h2></Rv>
    <Rv d={0.1}><p style={{fontSize:17,color:MT,lineHeight:1.85,marginBottom:18,maxWidth:640}}>Six layers in the platform. Seven capabilities across the company. The eighth is what transforms Sevyn8 from a product into a platform: System-Wide Learning. It observes outcomes across every device, every customer, every vertical. The 500th device deployed is genuinely smarter than the 1st. Not better hardware &mdash; more knowledge.</p></Rv>
    <Rv d={0.15}><p style={{fontSize:17,color:MT,lineHeight:1.85,maxWidth:640}}>The "8" is also, visually, an infinity loop turned upright &mdash; &#8734;. Competitors improve per device. Sevyn8 improves per system. The gap widens with every deployment. It never stops.</p></Rv>
  </Sc>

  <Sc bt><Rv><Tg c={V}>The team</Tg><h2 style={{...hd,fontSize:34,fontWeight:700,marginBottom:20}}>Built across two decades. Not assembled.</h2></Rv>
    <Rv d={0.1}><p style={{fontSize:17,color:MT,lineHeight:1.85,marginBottom:20,maxWidth:640}}>The founding team brings combined experience from Intel, Motorola, Qualcomm, OnePlus, Sony, Honeywell, ABB, IBM, and Micron. Over &#8377;500 Cr in hardware categories built, launched, and scaled. The leadership spans SoC architecture, firmware engineering, AI/ML research, vision science, go-to-market, and ecosystem partnerships &mdash; each person mapped to a layer of the stack.</p></Rv>
    <Rv d={0.15}><p style={{fontSize:17,color:T,fontWeight:500}}>Skills can be hired. Years of scars and playbooks can only be earned.</p></Rv>
  </Sc>

  <Sc bg={B2} bt><Rv><div style={{textAlign:"center",padding:"20px 0"}}><div style={{fontSize:12,textTransform:"uppercase",letterSpacing:3,color:T,fontWeight:600,marginBottom:14}}>The brand truth</div><p style={{...hd,fontSize:28,fontWeight:800}}>Sevyn is the full stack. <span style={{color:T}}>8 is what makes it compound.</span></p></div></Rv></Sc>

  <Sc bt><div style={{display:"flex",gap:48,flexWrap:"wrap",fontSize:16}}>{[{k:"Entity",v:"Sevyn8 Private Limited"},{k:"HQ",v:"New Delhi, India"},{k:"Status",v:"DPIIT Recognised Startup"}].map(function(i){return <div key={i.k}><div style={{fontSize:11,color:DM,textTransform:"uppercase",letterSpacing:1,marginBottom:4}}>{i.k}</div><div style={{fontWeight:500}}>{i.v}</div></div>})}</div></Sc>
</div>}

function ContactPg(){var t2=useState("enterprise"),ty=t2[0],is2={fontFamily:"inherit",fontSize:16,padding:"14px 18px",background:B2,border:"1px solid "+BD,borderRadius:7,color:TX,outline:"none",width:"100%"};
  var ph=ty==="enterprise"?"Tell us about your deployment needs, store/site count, and current camera infrastructure...":ty==="oem"?"Tell us about your product line, annual shipment volume, and target AI features...":"How can we help?";
  return <div style={{paddingTop:80}}><Sc><Rv><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:60,alignItems:"start"}}><div><Tg>Contact</Tg><h1 style={{...hd,fontSize:44,fontWeight:700,marginBottom:18}}>Start the conversation.</h1><p style={{fontSize:17,color:MT,lineHeight:1.8,marginBottom:36}}>Enterprise deployment. OEM integration. Platform evaluation.</p><div style={{fontSize:16,color:MT,lineHeight:1.8}}><div style={{fontSize:11,color:DM,textTransform:"uppercase",letterSpacing:1,marginBottom:5}}>Email</div><div style={{color:TX,fontWeight:500}}>hello@sevyn8.com</div><div style={{marginTop:18,fontSize:11,color:DM,textTransform:"uppercase",letterSpacing:1,marginBottom:5}}>Location</div><div>New Delhi, India</div></div></div><div><div style={{display:"flex",gap:6,marginBottom:18}}>{[["enterprise","Enterprise"],["oem","OEM Partner"],["general","General"]].map(function(x){return <button key={x[0]} onClick={function(){t2[1](x[0])}} style={{padding:"8px 18px",borderRadius:6,fontSize:14,fontWeight:500,fontFamily:"inherit",border:"1px solid "+(ty===x[0]?T:BD),background:ty===x[0]?T+"12":"transparent",color:ty===x[0]?T:MT,cursor:"pointer"}}>{x[1]}</button>})}</div><div style={{display:"flex",flexDirection:"column",gap:10}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><input placeholder="Name" style={is2} /><input placeholder="Email" style={is2} /></div><input placeholder="Company" style={is2} />{ty==="enterprise"&&<input placeholder="Industry (Smart Home, Retail, Fleet, Food & Cold Storage)" style={is2} />}{ty==="oem"&&<input placeholder="Annual device volume" style={is2} />}<textarea placeholder={ph} rows={4} style={{...is2,resize:"vertical"}} /><button style={{...bn,alignSelf:"flex-start"}}>Send message {"→"}</button></div></div></div></Rv></Sc></div>}

function Nav(p){var pg=p.pg,go=p.go,s2=useState(false),d2=useState(null);
  useEffect(function(){var h=function(){s2[1](window.scrollY>40)};window.addEventListener("scroll",h);return function(){window.removeEventListener("scroll",h)}},[]);
  var nl=function(l,t){return <span onClick={function(){go(t)}} style={{fontSize:14,fontWeight:500,color:pg===t?T:MT,cursor:"pointer"}}>{l}</span>};
  return <nav style={{position:"fixed",top:0,left:0,right:0,zIndex:999,padding:"0 40px",background:s2[0]?"rgba(6,8,16,.94)":"transparent",backdropFilter:s2[0]?"blur(20px)":"none",borderBottom:s2[0]?"1px solid "+BD:"none",transition:"all .3s"}}><div style={{maxWidth:1200,margin:"0 auto",display:"flex",alignItems:"center",justifyContent:"space-between",height:60}}><div onClick={function(){go("home")}} style={{cursor:"pointer",display:"flex",alignItems:"center",gap:8}}><div style={{width:26,height:26,borderRadius:5,background:"linear-gradient(135deg,"+T+","+BL+")",display:"flex",alignItems:"center",justifyContent:"center",fontSize:11,fontWeight:800,color:BG}}>S8</div><span style={{fontSize:16,fontWeight:800,letterSpacing:2}}>SEVYN8</span></div><div style={{display:"flex",alignItems:"center",gap:26}}>{nl("Platform","platform")}{nl("Edge AI Box","box")}<div style={{position:"relative"}} onMouseEnter={function(){d2[1]("s")}} onMouseLeave={function(){d2[1](null)}}><span style={{fontSize:14,fontWeight:500,color:pg.startsWith("sol-")?T:MT,cursor:"pointer",padding:"8px 0"}}>Solutions &#9662;</span>{d2[0]==="s"&&<div style={{position:"absolute",top:"100%",left:"50%",transform:"translateX(-50%)",paddingTop:8,zIndex:100}}><div style={{background:B2,border:"1px solid "+BD,borderRadius:10,padding:6,minWidth:280,boxShadow:"0 16px 48px rgba(0,0,0,.5)"}}>{SOL.map(function(s){return <div key={s.id} onClick={function(){go("sol-"+s.id)}} style={{padding:"10px 16px",borderRadius:7,cursor:"pointer",fontSize:14,color:TX}}>{s.n}<br/><span style={{fontSize:12,color:DM}}>{s.ln}</span></div>})}</div></div>}</div>{nl("Partners","partners")}<div style={{position:"relative"}} onMouseEnter={function(){d2[1]("c")}} onMouseLeave={function(){d2[1](null)}}><span style={{fontSize:14,fontWeight:500,color:["about","contact"].includes(pg)?T:MT,cursor:"pointer",padding:"8px 0"}}>Our Story &#9662;</span>{d2[0]==="c"&&<div style={{position:"absolute",top:"100%",right:0,paddingTop:8,zIndex:100}}><div style={{background:B2,border:"1px solid "+BD,borderRadius:10,padding:6,minWidth:150,boxShadow:"0 16px 48px rgba(0,0,0,.5)"}}>{[["Our Story","about"],["Contact","contact"]].map(function(x){return <div key={x[0]} onClick={function(){go(x[1])}} style={{padding:"10px 16px",borderRadius:7,cursor:"pointer",fontSize:14,color:TX}}>{x[0]}</div>})}</div></div>}</div><button style={{...bn,padding:"8px 20px",fontSize:13}} onClick={function(){go("contact")}}>Contact</button></div></div></nav>}

function Ft(){return <footer style={{borderTop:"1px solid "+BD,background:B2,padding:"36px 40px"}}><div style={{maxWidth:1200,margin:"0 auto",display:"flex",justifyContent:"space-between",alignItems:"center",fontSize:13,color:DM,flexWrap:"wrap",gap:12}}><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:20,height:20,borderRadius:4,background:"linear-gradient(135deg,"+T+","+BL+")",display:"flex",alignItems:"center",justifyContent:"center",fontSize:9,fontWeight:800,color:BG}}>S8</div><span style={{fontWeight:800,letterSpacing:2}}>SEVYN8</span></div><span>2026 Sevyn8 Private Limited &middot; New Delhi &middot; DPIIT Recognised</span></div></footer>}

export default function App(){
  var p2=useState("home"),pg=p2[0];
  useEffect(function(){var id="G-XXXXXXXXXX";var s=document.createElement("script");s.src="https://www.googletagmanager.com/gtag/js?id="+id;s.async=true;document.head.appendChild(s);window.dataLayer=window.dataLayer||[];function gtag(){window.dataLayer.push(arguments)}window.gtag=gtag;gtag("js",new Date());gtag("config",id)},[]);
  useEffect(function(){if(window.gtag)window.gtag("event","page_view",{page_title:pg,page_path:"/"+pg})},[pg]);
  useEffect(function(){document.title="Sevyn8 | AI at Edge Platform";[{name:"description",content:"Sevyn8 is an AI at Edge Platform. SoC-agnostic. Under 100ms inference, fully offline. Smart Home, Retail, Fleet, Cold Storage."},{name:"keywords",content:"edge AI, AI platform, edge computing, SoC agnostic, HAL, on-device AI, computer vision, IoT, fleet intelligence, OEM licensing, cold chain, food safety, smart home, retail analytics"},{property:"og:title",content:"Sevyn8 | Intelligence at the Edge"},{property:"og:description",content:"The AI at Edge Platform. Six layers. One device. Four industries."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"},{name:"robots",content:"index, follow"}].forEach(function(m){var el=document.createElement("meta");if(m.name)el.name=m.name;if(m.property)el.setAttribute("property",m.property);el.content=m.content;document.head.appendChild(el)})},[]);
  var go=useCallback(function(p){p2[1](p);window.scrollTo({top:0,behavior:"instant"})},[]);
  var C;if(pg==="home")C=<Home go={go}/>;else if(pg==="platform")C=<PlatPg go={go}/>;else if(pg==="box")C=<BoxPg go={go}/>;else if(pg==="partners")C=<PartPg go={go}/>;else if(pg==="about")C=<AboutPg />;else if(pg==="contact")C=<ContactPg />;else if(pg.indexOf("sol-")===0){var s=SOL.find(function(x){return "sol-"+x.id===pg});C=s?<SolPg s={s} go={go}/>:<Home go={go}/>}else C=<Home go={go}/>;
  return <div style={{minHeight:"100vh",background:BG,fontFamily:"'DM Sans',system-ui,sans-serif",WebkitFontSmoothing:"antialiased",color:TX,fontSize:16,lineHeight:1.65}}>
    <style dangerouslySetInnerHTML={{__html:"@import url('https://cdn.jsdelivr.net/npm/@fontsource-variable/outfit/index.min.css');@import url('https://cdn.jsdelivr.net/npm/@fontsource/dm-sans@5.0.3/400.css');@import url('https://cdn.jsdelivr.net/npm/@fontsource/dm-sans@5.0.3/500.css');@import url('https://cdn.jsdelivr.net/npm/@fontsource/dm-sans@5.0.3/700.css');*{margin:0;padding:0;box-sizing:border-box}::selection{background:#00D4AA;color:#060810}html{scroll-behavior:smooth}"}} />
    <Nav pg={pg} go={go}/><main key={pg}>{C}</main><Ft />
  </div>;
}
