import {useState, useEffect, useRef, useCallback} from "react";

var T="#00D4AA", BL="#38BDF8", V="#A78BFA", AM="#FBBF24", PK="#F472B6";
var BG="#060810", B2="#0B0F18", B3="#141924", TX="#E2E8F0", MT="#64748B", DM="#3B4559", BD="rgba(140,160,200,0.07)";
var hd={fontFamily:"'Outfit Variable',Outfit,system-ui",letterSpacing:"-.03em"};
var bn={display:"inline-flex",alignItems:"center",gap:6,padding:"12px 24px",background:T,color:BG,fontWeight:600,fontSize:14,border:"none",borderRadius:6,cursor:"pointer",fontFamily:"inherit"};
var b2={display:"inline-flex",alignItems:"center",gap:6,padding:"12px 24px",background:"transparent",color:TX,fontWeight:500,fontSize:14,border:"1px solid rgba(140,160,200,.15)",borderRadius:6,cursor:"pointer",fontFamily:"inherit"};
function Sc(p){return <section style={{borderTop:p.bt?"1px solid "+BD:"none",background:p.bg||"transparent"}}><div style={{maxWidth:960,margin:"0 auto",padding:"72px 40px"}}>{p.children}</div></section>}
function Tg(p){return <div style={{fontSize:11,textTransform:"uppercase",letterSpacing:3,color:p.c||T,marginBottom:12,fontWeight:500}}>{p.children}</div>}
function Rv(p){var r=useRef(null),v=useState(false);useEffect(function(){var el=r.current;if(!el)return;var o=new IntersectionObserver(function(e){if(e[0].isIntersecting){v[1](true);o.disconnect()}},{threshold:0.08});o.observe(el);return function(){o.disconnect()}},[]);return <div ref={r} style={{opacity:v[0]?1:0,transform:v[0]?"none":"translateY(24px)",transition:"all .7s cubic-bezier(.22,1,.36,1) "+(p.d||0)+"s"}}>{p.children}</div>}

var SOL=[
{id:"home",n:"Smart Home",ic:"□",ln:"Security · Senior care · Privacy-first",h:"Your cameras should know who is at the door — without the cloud.",d:"60% of smart camera owners mute notifications within 90 days. Every branch, car, and cat triggers the same alert. Sevyn8 runs AI on-device, distinguishing family from strangers, packages from shadows, threats from cats. No footage leaves your home. Ever.",wf:"TP-Link, Ring, and Arlo depend entirely on cloud. When WiFi drops, security disappears. Open-source Frigate requires expertise. None offer contextual decisioning — they detect motion, not meaning.",cs:["Person recognition — Family, friends, delivery regulars identified on-device. Strangers flagged","Package detection — Delivery events identified, passing traffic eliminated","Pet discrimination — Eliminates the #1 source of false alerts in residential systems","Senior care — Fall detection, gait anomaly tracking, irregular routine alerts","Privacy architecture — All AI runs locally on the Hub. No footage uploaded. Ever"],st:[{v:"60%",l:"Users mute in 90d"},{v:"3-5",l:"vs 90 daily alerts"},{v:"100%",l:"On-device"},{v:"₹499-999",l:"Cloud/mo"}],dp:["Buy the Sevyn8 Hub. Connect existing cameras. Intelligence starts in minutes.","Optional cloud at ₹499-999/month unlocks fleet learning, analytics, remote dashboard.","90 generic alerts become 3-5 actionable decisions. Trust rebuilds."]},
{id:"retail",n:"Retail",ic:"◆",ln:"Shelf intelligence · Pilferage · Footfall",h:"Shelf intelligence. Pilferage detection. Footfall that counts.",d:"Indian retail loses over ₹4,200 Cr annually to shrinkage. Sevyn8 turns passive CCTV into active loss prevention — detecting concealment in real time, monitoring shelves every 15 minutes, tracking zone-level conversion with 98%+ accuracy.",wf:"Hikvision and Dahua sell hardware, not intelligence. Wobot AI and Staqu overlay cloud analytics on existing NVRs — cannot run on-device, cannot learn across stores, fail when connectivity drops.",cs:["Pilferage detection — Behavioural analysis identifies concealment, repeat offenders flagged fleet-wide","Shelf compliance — Planogram verification every 15 minutes with automated deviation alerts","Footfall analytics — Zone-level heatmaps with 98%+ accuracy, dwell time, conversion tracking","Queue management — Real-time staffing alerts when wait times exceed thresholds","Shrinkage trending — Fleet-wide pattern recognition identifies systemic loss vectors"],st:[{v:"₹4,200Cr",l:"Annual shrinkage"},{v:"40-60%",l:"Loss reduction"},{v:"98%+",l:"Footfall accuracy"},{v:"3-6×",l:"ROI in 6 months"}],dp:["POC: 10-20 cameras, one floor, existing infra. Measurable shrinkage reduction in 60 days.","Multi-store fleet learning. Store #50 inherits intelligence from stores #1 through #49.","3-6× ROI in 6 months. Average enterprise deal: ₹171L."]},
{id:"fleet",n:"Fleet & Logistics",ic:"▲",ln:"Driver safety · Warehouse ops · Compliance",h:"12 million trucks on Indian roads. Almost none can see.",d:"India’s commercial fleet exceeds 12 million vehicles. The Motor Vehicle Amendment Act is pushing dashcam adoption. Yet fleet telematics track GPS and OBD — zero vision intelligence. Sevyn8 deploys on dashcams and facility cameras for continuous real-time oversight.",wf:"Fleet telematics track GPS and engine data but have zero vision capability. Camera vendors sell recording hardware with no on-device AI. No solution combines driver monitoring, PPE, facility safety, and predictive maintenance on one offline edge platform.",cs:["Driver monitoring — Fatigue and distraction detection with real-time in-cab audio intervention","Road-facing AI — Lane departure, tailgating, forward collision warning on dashcam SoC","PPE compliance — Hard hat, vest, gloves verified continuously, not during audits","Facility safety — Forklift proximity, restricted zones, loading dock monitoring, near-miss tracking","Predictive maintenance — Vibration and thermal anomaly detection on vehicles and equipment"],st:[{v:"12M+",l:"Indian fleet"},{v:"₹12,000Cr",l:"Annual ops+safety"},{v:"60%",l:"Incident reduction"},{v:"35+",l:"Sites by Y3"}],dp:["POC: Single facility or 50-vehicle fleet. Incidents, compliance, near-misses visible in 60 days.","Multi-site fleet learning reveals cross-location and cross-route patterns. 3-5 sites after POC.","Compliance automated and auditable. Contracts grow ₹68L to ₹171L by Y3."]},
{id:"coldchain",n:"Food & Cold Storage",ic:"○",ln:"Temperature AI · Contamination · FSSAI",h:"Every cold chain break is invisible until it is too late.",d:"India loses over ₹92,000 Cr of food annually to post-harvest wastage — 25-30% from cold chain failures. Temperature loggers record breaches after damage. Sevyn8 fuses thermal cameras, IoT sensors, and vision AI to predict deviations before they become breaches.",wf:"Temperature loggers are reactive — they record after damage. CCTV in food facilities is security-only. FSSAI compliance relies on checklists and periodic audits. No solution combines predictive temperature, contamination detection, and compliance on one edge platform.",cs:["Predictive temperature — Thermal camera + IoT fusion predicts deviation 15-30 min before breach","Contamination detection — Vision AI identifies foreign objects, pest intrusion, hygiene violations","FSSAI compliance — Automated worker hygiene, PPE (hairnets, gloves, aprons), sanitation monitoring","Door discipline — Cold room open-time tracking with alerts when duration exceeds safe limits","Inventory intelligence — FIFO compliance, expiry risk scoring, stock rotation via camera analytics"],st:[{v:"₹92,000Cr",l:"Food wastage/yr"},{v:"25-30%",l:"Cold chain losses"},{v:"15-30min",l:"Early warning"},{v:"100%",l:"Automated FSSAI"}],dp:["POC: One cold storage or processing unit. Thermal + IoT on existing infra. Validated in 60 days.","Multi-facility fleet learning. Facility #10 benefits from patterns across #1-9.","Cold chain losses down 40-60%. FSSAI audit prep: weeks to hours."]},
];

function HeroAnim(){
  var cv=useRef(null);
  useEffect(function(){
    var c=cv.current;if(!c)return;
    var x=c.getContext("2d"),W,H,af,pts=[];
    var rs=function(){var d=Math.min(window.devicePixelRatio||1,2);W=c.offsetWidth;H=c.offsetHeight;c.width=W*d;c.height=H*d;x.setTransform(d,0,0,d,0,0)};
    var sp=function(sx,sy,ex,ey,cl){pts.push({sx:sx,sy:sy,ex:ex,ey:ey,t:-Math.random()*.3,c:cl,s:.005+Math.random()*.004})};
    var rgb=function(c2){return c2===T?"0,212,170":c2===BL?"56,189,248":c2===V?"167,139,250":c2===AM?"251,191,36":"244,114,182"};
    var rr=function(a,b,w,h,r){x.beginPath();x.moveTo(a+r,b);x.lineTo(a+w-r,b);x.quadraticCurveTo(a+w,b,a+w,b+r);x.lineTo(a+w,b+h-r);x.quadraticCurveTo(a+w,b+h,a+w-r,b+h);x.lineTo(a+r,b+h);x.quadraticCurveTo(a,b+h,a,b+h-r);x.lineTo(a,b+r);x.quadraticCurveTo(a,b,a+r,b);x.closePath()};
    var oc=[T,AM,V,BL];
    var draw=function(t){
      x.clearRect(0,0,W,H);var s=t*.001;
      var bx=W*.5,by=H*.5,bw=130,bh=170;
      var gp=.5+Math.sin(s*1.3)*.2;
      x.shadowColor="rgba(0,212,170,"+(0.15*gp)+")";x.shadowBlur=50;
      rr(bx-bw/2,by-bh/2,bw,bh,14);x.fillStyle=B2;x.fill();x.shadowBlur=0;
      x.strokeStyle="rgba(0,212,170,"+(0.3+gp*.15)+")";x.lineWidth=1.2;x.stroke();
      x.setLineDash([3,5]);x.lineWidth=.5;
      for(var i=0;i<4;i++){var ly=H*(.15+i*.23);x.beginPath();x.moveTo(10,ly);var mx=(10+bx-bw/2)/2;x.bezierCurveTo(mx,ly,mx,by+(i-1.5)*20,bx-bw/2,by+(i-1.5)*20);x.strokeStyle="rgba(0,212,170,.08)";x.stroke();if(Math.random()<.03)sp(10,ly,bx-bw/2,by+(i-1.5)*20,T)}
      for(var i=0;i<4;i++){var ry=H*(.15+i*.23);x.beginPath();x.moveTo(bx+bw/2,by+(i-1.5)*20);var mx2=(bx+bw/2+W-10)/2;x.bezierCurveTo(mx2,by+(i-1.5)*20,mx2,ry,W-10,ry);x.strokeStyle="rgba("+rgb(oc[i])+",.06)";x.stroke();if(Math.random()<.02)sp(bx+bw/2,by+(i-1.5)*20,W-10,ry,oc[i])}
      x.setLineDash([]);
      for(var i=pts.length-1;i>=0;i--){var p=pts[i];p.t+=p.s;if(p.t>1){pts.splice(i,1);continue}if(p.t<0)continue;var e=p.t<.5?2*p.t*p.t:1-Math.pow(-2*p.t+2,2)/2;var px=p.sx+(p.ex-p.sx)*e,py=p.sy+(p.ey-p.sy)*e+Math.sin(e*Math.PI*3)*6;var al=Math.sin(p.t*Math.PI),r2=rgb(p.c);x.shadowColor="rgba("+r2+",.5)";x.shadowBlur=8;x.beginPath();x.arc(px,py,2.5,0,Math.PI*2);x.fillStyle="rgba("+r2+","+al*.85+")";x.fill();x.shadowBlur=0;for(var j=1;j<=3;j++){var tr=Math.max(0,p.t-j*.02),te=tr<.5?2*tr*tr:1-Math.pow(-2*tr+2,2)/2;x.beginPath();x.arc(p.sx+(p.ex-p.sx)*te,p.sy+(p.ey-p.sy)*te+Math.sin(te*Math.PI*3)*6,1.8-j*.35,0,Math.PI*2);x.fillStyle="rgba("+r2+","+al*.12*(1-j/3)+")";x.fill()}}
      af=requestAnimationFrame(draw)};
    rs();af=requestAnimationFrame(draw);window.addEventListener("resize",rs);
    return function(){cancelAnimationFrame(af);window.removeEventListener("resize",rs)};
  },[]);
  var devs=["IP Camera","Thermal","IoT Sensor","PTZ Camera"];
  var outs=[{l:"Dashboard",c:T},{l:"Smart Alert",c:AM},{l:"OTA Update",c:V},{l:"Partner API",c:BL}];
  var lb={position:"absolute",padding:"8px 14px",borderRadius:7,background:B3,fontSize:13,fontWeight:600,color:"#94A3B8",whiteSpace:"nowrap",border:"1px solid rgba(0,212,170,.18)",zIndex:3};
  return (<div style={{position:"relative",width:"100%",height:"100%"}}>
    <canvas ref={cv} style={{position:"absolute",inset:0,width:"100%",height:"100%"}} />
    {devs.map(function(d,i){return <div key={"d"+i} style={{...lb,left:0,top:(11+i*23)+"%",transform:"translateY(-50%)"}}>{d}</div>})}
    <div style={{position:"absolute",left:"50%",top:"50%",transform:"translate(-50%,-50%)",width:130,height:170,borderRadius:14,border:"1.5px solid "+T+"40",background:B2,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:7,zIndex:3,boxShadow:"0 0 50px "+T+"10"}}>
      <div style={{fontSize:14,fontWeight:700,color:T,letterSpacing:1}}>EDGE AI BOX</div>
      <div style={{fontSize:10,color:DM}}>100 TOPS &middot; &lt;100ms</div>
      {[{l:"HAL",c:T},{l:"AI Engine",c:BL},{l:"Decisioning",c:V}].map(function(la,i){return <div key={i} style={{padding:"4px 12px",borderRadius:5,border:"1px solid "+la.c+"35",background:la.c+"10",fontSize:11,fontWeight:600,color:la.c}}>{la.l}</div>})}
    </div>
    {outs.map(function(o,i){return <div key={"o"+i} style={{...lb,right:0,top:(11+i*23)+"%",transform:"translateY(-50%)",color:o.c,border:"1px solid "+o.c+"25"}}>{o.l}</div>})}
  </div>);
}

function BoxSchematic(){
  var layers=[{n:"System-Wide Learning",sub:"The moat — observes all outcomes, compounds fleet-wide, OTA to every device",c:AM},{n:"Integrations",sub:"B2B dashboards · B2C app · OEM white-label · Partner APIs",c:PK},{n:"Contextual Decisioning",sub:"Learns routines · Baselines · 3 AM person ≠ 3 PM person",c:V},{n:"Edge AI Engine",sub:"YOLOv8 · EfficientNet · INT8 quantised · <100ms · <2W",c:BL},{n:"HAL",sub:"Single API across multiple ARM and x86 SoC families. New hardware becomes a supply decision, not an engineering rewrite.",c:T}];
  var al=useState(null),a=al[0],pp=useState(0);
  useEffect(function(){var id=setInterval(function(){pp[1](function(v){return(v+1)%5})},900);return function(){clearInterval(id)}},[]);
  return (<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:40,alignItems:"start"}}>
    <div><div style={{background:B2,border:"2px solid "+T+"35",borderRadius:20,overflow:"hidden",boxShadow:"0 0 80px "+T+"0C,0 20px 60px rgba(0,0,0,.4)"}}>
      <div style={{background:"linear-gradient(180deg,"+T+"12,transparent)",padding:"24px 24px 16px",borderBottom:"1px solid "+BD}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontSize:18,fontWeight:700,color:T,letterSpacing:1.5}}>EDGE AI BOX</div><div style={{fontSize:12,color:DM,marginTop:2}}>Sevyn8 Platform Device</div></div><div style={{display:"flex",gap:4}}>{[T,BL,V].map(function(c,i){return <div key={i} style={{width:8,height:8,borderRadius:"50%",background:c,opacity:pp[0]===i?1:.25,transition:"opacity .4s",boxShadow:pp[0]===i?"0 0 8px "+c:"none"}} />})}</div></div></div>
      <div style={{padding:"16px 20px"}}>{layers.map(function(la,i){var isA=pp[0]===i;return <div key={i} style={{display:"flex",alignItems:"center",gap:10,padding:"8px 12px",marginBottom:4,borderRadius:8,background:isA?la.c+"12":"transparent",borderLeft:"3px solid "+(isA?la.c:la.c+"30"),transition:"all .4s"}}><div style={{width:6,height:6,borderRadius:"50%",background:la.c,boxShadow:isA?"0 0 8px "+la.c:"none"}} /><span style={{fontSize:13,fontWeight:isA?600:500,color:isA?la.c:DM}}>{la.n}</span>{isA&&<div style={{marginLeft:"auto",fontSize:10,color:la.c,fontWeight:600}}>ACTIVE</div>}</div>})}</div>
      <div style={{padding:"12px 20px 16px",borderTop:"1px solid "+BD,display:"flex",gap:20,justifyContent:"center"}}>{[{l:"100 TOPS",s:"AI Compute"},{l:"<100ms",s:"Latency"},{l:"<2W",s:"Power"},{l:"Offline",s:"Mode"}].map(function(s,i){return <div key={i} style={{textAlign:"center"}}><div style={{fontSize:14,fontWeight:700,color:[T,BL,V,AM][i]}}>{s.l}</div><div style={{fontSize:9,color:DM,marginTop:1}}>{s.s}</div></div>})}</div>
      <div style={{padding:"0 20px 16px",display:"flex",gap:6,justifyContent:"center"}}>{["WiFi 6","LTE","BLE 5.4","Thread"].map(function(c){return <span key={c} style={{fontSize:10,padding:"3px 10px",borderRadius:4,border:"1px solid "+BD,color:DM}}>{c}</span>})}</div>
    </div><div style={{display:"flex",justifyContent:"center",gap:28,marginTop:16}}>{[{l:"PoE In",c:T},{l:"USB 3.0",c:BL},{l:"HDMI",c:V}].map(function(port,i){return <div key={i} style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:10,height:10,borderRadius:2,border:"1.5px solid "+port.c,background:port.c+"15"}} /><span style={{fontSize:11,color:DM}}>{port.l}</span></div>})}</div></div>
    <div style={{display:"flex",flexDirection:"column",gap:8}}><div style={{fontSize:11,textTransform:"uppercase",letterSpacing:3,color:DM,marginBottom:4,fontWeight:500}}>Platform layers</div>{layers.map(function(la,i){var active=a===i;return <div key={i} onClick={function(){al[1](active?null:i)}} style={{padding:"14px 18px",borderRadius:10,background:active?BG:B3,border:"1.5px solid "+(active?la.c+"55":BD),borderLeft:"4px solid "+la.c,cursor:"pointer",transition:"all .3s"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:15,fontWeight:600,color:active?TX:MT}}>{la.n}</span><span style={{fontSize:18,color:la.c,transition:"transform .3s",transform:active?"rotate(45deg)":"none",lineHeight:1}}>+</span></div>{active&&<p style={{fontSize:14,color:MT,lineHeight:1.7,marginTop:10}}>{la.sub}</p>}</div>})}</div>
  </div>);
}

function Pipe(){var s2=useState(0),st=s2[0];useEffect(function(){var id=setInterval(function(){s2[1](function(s){return(s+1)%5})},2400);return function(){clearInterval(id)}},[]);
  var S=[{l:"Raw feed",c:DM,d:"4K video from IP camera, thermal sensor, or IoT device enters the Edge AI Box."},{l:"HAL",c:T,d:"Hardware Abstraction Layer normalises across multiple ARM and x86 SoC families. SoC-agnostic by design."},{l:"AI Engine",c:BL,d:"YOLOv8 + EfficientNet INT8 on-device. Under 100ms, under 2W. Fully offline."},{l:"Decisioning",c:V,d:"Context engine applies learned routines. A person at 3 AM differs from 3 PM."},{l:"Action",c:AM,d:"Alert sent. Compliance logged. Dashboard updated. OTA improvement queued fleet-wide."}];
  return (<div><div style={{display:"flex",alignItems:"center",marginBottom:22}}>{S.map(function(s,i){return <div key={i} style={{flex:1,display:"flex",alignItems:"center",cursor:"pointer"}} onClick={function(){s2[1](i)}}><div style={{flex:"0 0 auto",width:80,padding:"12px 0",borderRadius:8,background:st===i?s.c+"15":"transparent",border:"1.5px solid "+(st>=i?s.c+"55":BD),textAlign:"center",transition:"all .4s",boxShadow:st===i?"0 0 16px "+s.c+"22":"none"}}><div style={{width:8,height:8,borderRadius:"50%",margin:"0 auto 6px",background:st>=i?s.c:DM,boxShadow:st===i?"0 0 12px "+s.c:"none"}} /><div style={{fontSize:11,fontWeight:600,color:st>=i?TX:DM}}>{s.l}</div></div>{i<4&&<div style={{flex:1,height:2,position:"relative",margin:"0 -1px"}}><div style={{position:"absolute",inset:0,background:BD}} /><div style={{position:"absolute",top:0,left:0,height:"100%",width:st>i?"100%":st===i?"50%":"0%",background:"linear-gradient(90deg,"+S[i].c+","+S[Math.min(i+1,4)].c+")",transition:"width .5s"}} /></div>}</div>})}</div><div style={{background:B2,border:"1px solid "+S[st].c+"25",borderRadius:10,padding:"20px 24px",borderLeft:"3px solid "+S[st].c}}><div style={{fontSize:16,fontWeight:600,color:S[st].c,marginBottom:6}}>{S[st].l}</div><div style={{fontSize:16,color:MT,lineHeight:1.75}}>{S[st].d}</div></div></div>)}

function Ctx(){var s2=useState(0),sc=s2[0];useEffect(function(){var id=setInterval(function(){s2[1](function(s){return(s+1)%6})},3000);return function(){clearInterval(id)}},[]);
  var S=[{t:"Person at door — 3:17 AM",x:"Unknown face · Unusual hour",dc:"⚠ Alert homeowner",c:AM},{t:"Person at door — 2:30 PM",x:"Amazon delivery · Package expected",dc:"✓ Log silently",c:T},{t:"Person near shelf 4+ min",x:"Repeated reach · No basket",dc:"⚠ Concealment alert",c:PK},{t:"Cold room door open 4+ min",x:"Loading ended · No pick order",dc:"⚠ Breach imminent",c:V},{t:"Driver eyes closed 3+ sec",x:"Highway · Night shift · 6 hrs in",dc:"⚠ In-cab alert + fleet",c:AM},{t:"Forklift entering Zone C",x:"Pedestrian · No hard hat",dc:"⚠ Proximity + PPE log",c:PK}],s=S[sc];
  return (<div style={{maxWidth:600}}><div style={{display:"flex",gap:4,marginBottom:18}}>{S.map(function(z,i){return <div key={i} onClick={function(){s2[1](i)}} style={{flex:1,height:4,borderRadius:2,cursor:"pointer",background:i===sc?s.c:BD}} />})}</div>{[{l:"Detection",v:s.t},{l:"Context",v:s.x},{l:"Decision",v:s.dc}].map(function(r,i){return <div key={sc+"-"+i} style={{display:"flex",gap:18,alignItems:"center",padding:"16px 22px",marginBottom:6,background:i===2?s.c+"0D":B2,border:"1.5px solid "+(i===2?s.c+"44":BD),borderRadius:10}}><div style={{fontSize:11,textTransform:"uppercase",letterSpacing:1.5,color:DM,minWidth:68,fontWeight:600}}>{r.l}</div><div style={{width:1,height:20,background:BD}} /><div style={{fontSize:16,color:i===0?MT:s.c,fontWeight:i===2?600:400}}>{r.v}</div></div>})}</div>)}

function Fleet(){var p2=useState(-1),p=p2[0];useEffect(function(){var id=setInterval(function(){p2[1](function(v){return(v+1)%6})},1000);return function(){clearInterval(id)}},[]);
  var N=[{x:18,y:8,l:"Retail #1"},{x:52,y:3,l:"Retail #2"},{x:84,y:10,l:"Cold Store"},{x:10,y:82,l:"Fleet Hub"},{x:50,y:94,l:"Home"},{x:88,y:80,l:"Warehouse"}];
  return (<div style={{position:"relative",height:300,maxWidth:560}}><div style={{position:"absolute",left:"50%",top:"50%",transform:"translate(-50%,-50%)",width:90,height:90,borderRadius:"50%",background:"radial-gradient(circle,"+T+"1A,transparent)",border:"1.5px solid "+T+"40",display:"flex",alignItems:"center",justifyContent:"center",flexDirection:"column",zIndex:2,boxShadow:"0 0 40px "+T+"14"}}><div style={{fontSize:13,fontWeight:700,color:T}}>OTA</div><div style={{fontSize:10,color:MT}}>Fleet update</div></div>{N.map(function(n,i){return <div key={i}><svg style={{position:"absolute",inset:0,width:"100%",height:"100%",pointerEvents:"none"}}><line x1={n.x+"%"} y1={n.y+"%"} x2="50%" y2="50%" stroke={i<=p?T:BD} strokeWidth={i===p?1.5:.5} strokeDasharray={i<=p?"none":"4 7"} style={{transition:"all .5s"}} /></svg><div style={{position:"absolute",left:n.x+"%",top:n.y+"%",transform:"translate(-50%,-50%)",padding:"8px 16px",borderRadius:8,background:i===p?T+"1A":B3,border:"1.5px solid "+(i<=p?T+"50":BD),fontSize:14,fontWeight:500,color:i<=p?T:DM,transition:"all .5s",whiteSpace:"nowrap",zIndex:1}}>{n.l}{i<=p?" ✓":""}</div></div>})}</div>)}

function Outcomes(p){
  var items=[
    {v:"Retail",ic:"◆",c:T,id:"retail",before:"Cameras record everything. Nobody reviews the footage. Shrinkage costs ₹4,200 Cr annually.",after:"40-60% shrinkage reduction",metric:"₹4,200Cr",ml:"saved annually",detail:"Real-time concealment detection. Shelf compliance every 15 min. Footfall at 98%+ accuracy."},
    {v:"Smart Home",ic:"□",c:BL,id:"home",before:"90 alerts per day. Every branch, car, and cat triggers the same notification. 60% mute within 90 days.",after:"3-5 decisions that matter",metric:"97%",ml:"noise eliminated",detail:"Person recognition on-device. Family vs stranger vs delivery. No cloud. No footage leaving home."},
    {v:"Cold Storage",ic:"○",c:V,id:"coldchain",before:"Temperature loggers record breaches after the damage is done. ₹92,000 Cr in food wastage annually.",after:"Predicted 30 min early",metric:"40-60%",ml:"losses prevented",detail:"Thermal camera + IoT fusion. FSSAI compliance automated. Door discipline monitored continuously."},
    {v:"Fleet",ic:"▲",c:AM,id:"fleet",before:"Audits catch violations monthly. GPS tracks location, not behaviour. 12M+ trucks, almost none can see.",after:"Compliance is continuous",metric:"60%",ml:"fewer incidents",detail:"Driver fatigue intervention. PPE verified continuously. Predictive maintenance on equipment."}
  ];
  var s2=useState(0),active=s2[0],phase=useState("before"),ph=phase[0];
  useEffect(function(){
    var id=setInterval(function(){
      phase[1](function(p2){
        if(p2==="before") return "after";
        s2[1](function(a){return (a+1)%4});
        return "before";
      });
    },4000);
    return function(){clearInterval(id)};
  },[]);
  var it=items[active];
  return (<div>
    <div style={{display:"flex",gap:6,marginBottom:32,justifyContent:"center"}}>{items.map(function(item,i){return (
      <div key={i} onClick={function(){s2[1](i);phase[1]("before")}} style={{display:"flex",alignItems:"center",gap:8,padding:"10px 20px",borderRadius:8,cursor:"pointer",background:active===i?item.c+"12":"transparent",border:"1.5px solid "+(active===i?item.c+"44":BD),transition:"all .4s"}}>
        <span style={{fontSize:14,color:item.c}}>{item.ic}</span>
        <span style={{fontSize:14,fontWeight:active===i?600:500,color:active===i?TX:DM,transition:"color .3s"}}>{item.v}</span>
      </div>
    )})}</div>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:24,minHeight:200}}>
      <div style={{position:"relative",overflow:"hidden"}}>
        <div style={{opacity:ph==="before"?1:.5,transform:ph==="before"?"translateY(0)":"translateY(-8px)",transition:"all .6s cubic-bezier(.22,1,.36,1)",padding:32,borderRadius:14,border:"1.5px solid "+(ph==="before"?"rgba(140,160,200,.15)":BD),background:ph==="before"?B3:BG,height:"100%",display:"flex",flexDirection:"column",justifyContent:"center"}}>
          <div style={{fontSize:11,textTransform:"uppercase",letterSpacing:2,color:PK,marginBottom:12,fontWeight:600}}>Without Sevyn8</div>
          <p style={{fontSize:19,color:ph==="before"?TX:MT,lineHeight:1.7,transition:"color .4s"}}>{it.before}</p>
        </div>
      </div>
      <div style={{position:"relative",overflow:"hidden"}}>
        <div style={{opacity:ph==="after"?1:.15,transform:ph==="after"?"translateY(0)":"translateY(16px)",transition:"all .6s cubic-bezier(.22,1,.36,1) .15s",padding:32,borderRadius:14,border:"1.5px solid "+(ph==="after"?it.c+"55":BD),background:ph==="after"?it.c+"0A":BG,height:"100%",display:"flex",flexDirection:"column",justifyContent:"center",boxShadow:ph==="after"?"0 0 40px "+it.c+"12":"none"}}>
          <div style={{fontSize:10,textTransform:"uppercase",letterSpacing:2,color:it.c,marginBottom:12,fontWeight:500}}>With Sevyn8</div>
          <div style={{display:"flex",alignItems:"baseline",gap:12,marginBottom:12}}><span style={{...hd,fontSize:36,fontWeight:800,color:TX}}>{it.after}</span></div>
          <p style={{fontSize:15,color:MT,lineHeight:1.7,marginBottom:16}}>{it.detail}</p>
          <div style={{display:"inline-flex",alignItems:"center",gap:8,cursor:"pointer",color:it.c,fontSize:13,fontWeight:600}} onClick={function(){p.go("sol-"+it.id)}}>See {it.v.toLowerCase()} solution <span>{"→"}</span></div>
        </div>
      </div>
    </div>
    <div style={{display:"flex",justifyContent:"center",gap:4,marginTop:24}}>{items.map(function(item,i){return <div key={i} style={{width:active===i?32:8,height:4,borderRadius:2,background:active===i?item.c:BD,transition:"all .4s"}} />})}</div>
  </div>);
}

function Home(p){
  var go=p.go,l2=useState(false),ld=l2[0];
  useEffect(function(){setTimeout(function(){l2[1](true)},150)},[]);
  return (<div>
    <section style={{minHeight:"100vh",display:"flex",alignItems:"center",padding:"100px 40px 60px",maxWidth:1200,margin:"0 auto"}}>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:60,alignItems:"center",width:"100%"}}>
        <div style={{opacity:ld?1:0,transform:ld?"none":"translateY(24px)",transition:"all 1s cubic-bezier(.16,1,.3,1) .3s"}}>
          <div style={{display:"inline-flex",alignItems:"center",gap:7,padding:"5px 14px",border:"1px solid "+T+"28",borderRadius:16,marginBottom:28}}><div style={{width:7,height:7,borderRadius:"50%",background:T,boxShadow:"0 0 10px "+T}} /><span style={{fontSize:13,color:T,fontWeight:500}}>AI at Edge Platform</span></div>
          <h1 style={{...hd,fontSize:52,lineHeight:1.06,fontWeight:700,marginBottom:18}}>Intelligence at the edge.</h1>
          <p style={{fontSize:18,color:TX,lineHeight:1.8,marginBottom:24,maxWidth:440}}>90 daily alerts become 3 genuine decisions. Shrinkage drops 40-60%. Cold chain breaches predicted 30 minutes early. Fleet incidents cut by 60%.</p>
          <p style={{fontSize:15,color:DM,lineHeight:1.75,marginBottom:32,maxWidth:420}}>One device. Under 100ms. Fully offline. Four industries. No cloud required.</p>
          <div style={{display:"flex",gap:12}}><button style={bn} onClick={function(){go("platform")}}>See how it works</button><button style={b2} onClick={function(){go("contact")}}>Talk to us</button></div>
        </div>
        <div style={{position:"relative",height:480,opacity:ld?1:0,transition:"opacity 1.2s ease .6s"}}><HeroAnim /></div>
      </div>
    </section>

    <section style={{borderTop:"1px solid "+BD,background:B2}}><div style={{maxWidth:1100,margin:"0 auto",padding:"56px 40px"}}><Rv><div style={{textAlign:"center",marginBottom:40}}><Tg>What changes</Tg><h2 style={{...hd,fontSize:34,fontWeight:700}}>Before Sevyn8 vs. after.</h2></div></Rv>
      <Outcomes go={go} />
    </div></section>

    <Sc bg={B2} bt><Rv><Tg>How it works</Tg><h2 style={{...hd,fontSize:34,fontWeight:700,marginBottom:10}}>From raw sensor feed to decision in under 100ms</h2><p style={{fontSize:17,color:MT,marginBottom:34}}>Five stages. Click any to explore.</p></Rv><Rv d={.12}><Pipe /></Rv></Sc>
    <Sc><Rv><Tg c={V}>Contextual decisioning</Tg><h2 style={{...hd,fontSize:34,fontWeight:700,marginBottom:10}}>Same detection. Different decisions.</h2><p style={{fontSize:17,color:MT,marginBottom:34}}>The platform learns routines and only surfaces what matters.</p></Rv><Rv d={.12}><Ctx /></Rv></Sc>
    <Sc><Rv><Tg>Solutions</Tg><h2 style={{...hd,fontSize:34,fontWeight:700,marginBottom:34}}>Same platform. Four industries.</h2></Rv>{SOL.map(function(s,i){return <Rv key={i} d={i*.05}><div onClick={function(){go("sol-"+s.id)}} style={{display:"grid",gridTemplateColumns:"28px 160px 1fr 28px",gap:16,alignItems:"center",padding:"20px 12px",borderBottom:"1px solid "+BD,cursor:"pointer",borderRadius:6}}><span style={{fontSize:18,color:T}}>{s.ic}</span><span style={{fontSize:17,fontWeight:600}}>{s.n}</span><span style={{fontSize:15,color:MT}}>{s.ln}</span><span style={{color:DM,fontSize:18}}>{"→"}</span></div></Rv>})}</Sc>
    <Sc bg={B2} bt><Rv><Tg c={AM}>Fleet intelligence</Tg><h2 style={{...hd,fontSize:34,fontWeight:700,marginBottom:10}}>One device learns. Every device improves.</h2><p style={{fontSize:17,color:MT,marginBottom:34}}>Encrypted OTA. Federated learning. No raw data shared. Your 500th device is smarter than your 1st.</p></Rv><Rv d={.12}><Fleet /></Rv></Sc>
    <section style={{borderTop:"1px solid "+BD}}><div style={{maxWidth:1100,margin:"0 auto",padding:"44px 40px",display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:20}}><span style={{fontSize:12,textTransform:"uppercase",letterSpacing:2,color:DM}}>Technology ecosystem</span><div style={{display:"flex",gap:40,flexWrap:"wrap"}}>{["ARM SoC Partners","x86 SoC Partners","Security Silicon","Sensor Partners","Module Partners"].map(function(n){return <span key={n} style={{fontSize:13,fontWeight:600,letterSpacing:2,color:DM}}>{n}</span>})}</div></div></section>
    <Sc><Rv><div style={{textAlign:"center"}}><h2 style={{...hd,fontSize:34,fontWeight:700,marginBottom:14}}>Deploy intelligence.</h2><p style={{fontSize:17,color:MT,marginBottom:30}}>Enterprise deployment &middot; OEM licensing &middot; Platform evaluation</p><div style={{display:"flex",gap:12,justifyContent:"center"}}><button style={bn} onClick={function(){go("contact")}}>Get in touch</button><button style={b2} onClick={function(){go("partners")}}>Partner with us</button></div></div></Rv></Sc>
  </div>)}

function PlatPg(p){return <div style={{paddingTop:80}}><Sc><Rv><Tg>Platform</Tg><h1 style={{...hd,fontSize:46,fontWeight:700,marginBottom:18}}>Six layers. One intelligence substrate.</h1><p style={{fontSize:18,color:MT,lineHeight:1.8,maxWidth:500}}>System-Wide Learning at the apex. Compounding intelligence pushed to every device via OTA.</p></Rv></Sc><Sc bg={B2} bt><Rv><h2 style={{...hd,fontSize:32,fontWeight:700,marginBottom:30}}>Inference pipeline</h2></Rv><Rv d={.1}><Pipe /></Rv></Sc><Sc><Rv><h2 style={{...hd,fontSize:32,fontWeight:700,marginBottom:30}}>Contextual decisioning</h2></Rv><Rv d={.1}><Ctx /></Rv></Sc><Sc bg={B2} bt><Rv><h2 style={{...hd,fontSize:32,fontWeight:700,marginBottom:30}}>Fleet intelligence</h2></Rv><Rv d={.1}><Fleet /></Rv></Sc><Sc bt><Rv><div style={{textAlign:"center"}}><button style={bn} onClick={function(){p.go("box")}}>Edge AI Box {"→"}</button></div></Rv></Sc></div>}

function BoxPg(p){return <div style={{paddingTop:80}}><Sc><Rv><Tg c={BL}>Product</Tg><h1 style={{...hd,fontSize:46,fontWeight:700,marginBottom:18}}>Edge AI Box</h1><p style={{fontSize:18,color:MT,lineHeight:1.8,maxWidth:540}}>The entire Sevyn8 platform in one device. Any camera. Any SoC. Four industries.</p></Rv></Sc><Sc bg={B2} bt><Rv><BoxSchematic /></Rv></Sc><Sc><Rv><h3 style={{fontSize:11,textTransform:"uppercase",letterSpacing:3,color:DM,marginBottom:14}}>Connects to</h3><p style={{fontSize:16,color:MT,lineHeight:1.85}}>Fixed Box IP Camera &middot; Dome Camera &middot; Bullet Camera &middot; PTZ Camera &middot; Fisheye Panoramic &middot; Thermal LWIR &middot; ANPR Camera &middot; In-Cab IR Camera &middot; Shelf-Edge Camera &middot; WiFi Consumer Camera &middot; Video Doorbell &middot; IoT Sensor Nodes &middot; BLE Beacons &middot; RFID Readers</p></Rv></Sc><Sc bg={B2} bt><Rv><h3 style={{fontSize:11,textTransform:"uppercase",letterSpacing:3,color:DM,marginBottom:22}}>Specifications</h3></Rv><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(200px,1fr))",gap:10}}>{[{k:"AI compute",v:"Up to 100 TOPS"},{k:"Inference",v:"Under 100ms"},{k:"Power",v:"Under 2 watts"},{k:"Connectivity",v:"WiFi 6, LTE, BLE 5.4, Thread"},{k:"SoC",v:"ARM & x86 families supported"},{k:"Security",v:"STQC ER-1 through ER-5"},{k:"Compliance",v:"BIS CRS, DPDP, HIPAA"},{k:"Updates",v:"Encrypted OTA fleet-wide"}].map(function(s,i){return <Rv key={i} d={i*.04}><div style={{padding:"18px 20px",borderRadius:8,border:"1px solid "+BD,background:BG}}><div style={{fontSize:11,color:DM,textTransform:"uppercase",letterSpacing:1,marginBottom:5}}>{s.k}</div><div style={{fontSize:16,fontWeight:500}}>{s.v}</div></div></Rv>})}</div></Sc><Sc bt><Rv><div style={{textAlign:"center"}}><button style={bn} onClick={function(){p.go("contact")}}>Request evaluation unit</button></div></Rv></Sc></div>}

function SolPg(p){var s=p.s;return <div style={{paddingTop:80}}><Sc><Rv><div style={{fontSize:14,color:MT,marginBottom:16}}><span style={{color:T,cursor:"pointer"}} onClick={function(){p.go("home")}}>Solutions</span> / {s.n}</div><h1 style={{...hd,fontSize:44,fontWeight:700,lineHeight:1.08,maxWidth:600,marginBottom:22}}>{s.h}</h1><p style={{fontSize:18,color:MT,lineHeight:1.85,maxWidth:560}}>{s.d}</p></Rv></Sc>
  {s.st&&<section style={{borderTop:"1px solid "+BD,background:B2}}><div style={{maxWidth:960,margin:"0 auto",padding:"40px",display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14}}>{s.st.map(function(st,i){return <Rv key={i} d={i*.08}><div style={{padding:20,borderRadius:10,border:"1px solid "+BD,background:BG,textAlign:"center"}}><div style={{fontSize:28,fontWeight:700,...hd,color:T}}>{st.v}</div><div style={{fontSize:13,color:MT,marginTop:5}}>{st.l}</div></div></Rv>})}</div></section>}
  {s.wf&&<Sc bt><Rv><h3 style={{fontSize:11,textTransform:"uppercase",letterSpacing:3,color:PK,marginBottom:12}}>Why current solutions fail</h3><p style={{fontSize:16,color:MT,lineHeight:1.85,maxWidth:600}}>{s.wf}</p></Rv></Sc>}
  <Sc bg={B2} bt><Rv><h3 style={{fontSize:11,textTransform:"uppercase",letterSpacing:3,color:DM,marginBottom:22}}>What the platform sees</h3></Rv>{s.cs.map(function(c,i){var pts=c.split(" — ");return <Rv key={i} d={i*.05}><div style={{display:"flex",gap:16,padding:"16px 0",borderBottom:"1px solid "+BD}}><div style={{width:6,height:6,borderRadius:"50%",background:T,marginTop:9,flexShrink:0}} /><div><span style={{fontSize:16,fontWeight:600,color:TX}}>{pts[0]}</span>{pts[1]&&<span style={{fontSize:16,color:MT}}> &mdash; {pts[1]}</span>}</div></div></Rv>})}</Sc>
  <Sc bt><Rv><h3 style={{fontSize:11,textTransform:"uppercase",letterSpacing:3,color:DM,marginBottom:26}}>Deployment</h3></Rv><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:14}}>{["Prove","Scale","Result"].map(function(l,i){return <Rv key={i} d={i*.1}><div style={{padding:24,borderRadius:12,border:"1px solid "+BD,background:B2}}><div style={{fontSize:11,textTransform:"uppercase",letterSpacing:2,color:T,marginBottom:10,fontWeight:600}}>{l}</div><p style={{fontSize:15,color:MT,lineHeight:1.75}}>{s.dp[i]}</p></div></Rv>})}</div></Sc>
  <Sc bg={B2} bt><Rv><div style={{textAlign:"center"}}><button style={bn} onClick={function(){p.go("contact")}}>Deploy in {s.n.toLowerCase()} {"→"}</button></div></Rv></Sc></div>}

function PartPg(p){var cats=[{t:"Silicon Partners (ARM & x86)",i:[["Tier-1 Mobile SoC Provider","Leading ARM-based application processor with dedicated NPU delivering up to 8 TOPS. WiFi 6E integrated. Primary SoC for the Edge AI Box. Design Partnership Agreement signed.","ARM SoC"],["Vision-Grade SoC Provider","4 TOPS dedicated vision processor with 4K ISP. Camera-optimised silicon. STQC ER-5 certified, US-origin. Ideal for surveillance and smart city deployments.","ARM SoC"],["Low-Power IoT SoC Provider","LTE-M/NB-IoT cellular SoC for IoT gateways and BLE 5.4 SoC for ESL and sensor mesh networks. Ultra-low power for battery-operated edge nodes.","IoT SoC"]]},{t:"Security Silicon",i:[["Hardware Security Partner","TPM 2.0 for hardware root of trust. Dedicated secure element for device identity provisioning at scale. Secure MCU for isolated cryptographic operations. DPA signed.","Security"]]},{t:"Sensor & Module Partners",i:[["Global Image Sensor Leader","Industry-leading image sensor family for camera modules. High dynamic range and low-light performance optimised specifically for on-device edge AI inference.","Sensor"],["Pre-Certified Module Provider","Pre-certified LTE Cat1bis, WiFi 6, and secure MCU modules with WPC ETA certification. Saves each OEM partner significant per-SKU compliance cost and time.","Module"],["WiFi 6E Module Specialist","Pre-certified WiFi 6E modules for camera and gateway integration. Regulatory approvals included, accelerating OEM time-to-market.","Module"]]},{t:"Design Partners",i:[["Concept-to-product design","Industrial design, mechanical engineering, thermal management, and design-for-manufacturing for Edge AI Box and Hub hardware.","Design"],["System integration","Full AI-at-Edge stack deployment combining vision, IoT sensors, and edge compute into unified customer solutions.","Integration"]]}];
  return <div style={{paddingTop:80}}><Sc><Rv><Tg>Partners</Tg><h1 style={{...hd,fontSize:44,fontWeight:700,marginBottom:18,maxWidth:500}}>Technology partners. Intelligence infrastructure.</h1><p style={{fontSize:18,color:MT,lineHeight:1.8,maxWidth:540}}>Sevyn8 partners with world-class silicon, sensor, and design firms to build the most capable edge AI platform on the market. We work with the largest ARM and x86 SoC providers, leading global and niche sensor companies, and specialist design houses.</p></Rv></Sc>
    <Sc bg={B2} bt><Rv><h3 style={{fontSize:11,textTransform:"uppercase",letterSpacing:3,color:DM,marginBottom:22}}>OEM licensing model</h3></Rv><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}>{[["01","Embed","Sevyn8 platform — HAL, firmware, AI models, decisioning — integrates into your hardware at factory level"],["02","Ship","Your brand, your distribution, your customers. The intelligence inside is Sevyn8 — invisible platform, visible value"],["03","Monetise","One-time hardware sale becomes recurring SaaS revenue. Cloud AI upsell converts device buyers into subscribers"],["04","Compound","Fleet learning improves every device you ship. Your 100,000th unit outperforms your competitor's latest launch"]].map(function(s,i){return <Rv key={i} d={i*.08}><div style={{padding:22,borderRadius:10,border:"1px solid "+BD,background:BG}}><span style={{fontFamily:"monospace",fontSize:13,color:T}}>{s[0]}</span><h4 style={{fontSize:17,fontWeight:600,margin:"8px 0 5px"}}>{s[1]}</h4><p style={{fontSize:14,color:MT,lineHeight:1.7}}>{s[2]}</p></div></Rv>})}</div></Sc>
    {cats.map(function(cat,ci){return <Sc key={ci} bg={ci%2===0?undefined:B2} bt><Rv><h3 style={{fontSize:11,textTransform:"uppercase",letterSpacing:3,color:DM,marginBottom:22}}>{cat.t}</h3></Rv><div style={{display:"grid",gridTemplateColumns:cat.i.length>1?"1fr 1fr":"1fr",gap:12}}>{cat.i.map(function(q,j){return <Rv key={j} d={j*.06}><div style={{padding:22,borderRadius:10,border:"1px solid "+BD,background:ci%2===0?B2:BG}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><span style={{fontSize:17,fontWeight:700}}>{q[0]}</span><span style={{fontSize:11,color:T,padding:"4px 12px",border:"1px solid "+T+"25",borderRadius:5}}>{q[2]}</span></div><p style={{fontSize:15,color:MT,lineHeight:1.7}}>{q[1]}</p></div></Rv>})}</div></Sc>})}
    <Sc bg={B2} bt><Rv><h3 style={{fontSize:11,textTransform:"uppercase",letterSpacing:3,color:DM,marginBottom:22}}>Current customers</h3><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14}}><Rv d={0}><div style={{padding:24,borderRadius:12,border:"1px solid "+BD,background:BG}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10}}><span style={{fontSize:18,fontWeight:700}}>Global ESL Leader</span><span style={{fontSize:10,color:AM,padding:"3px 10px",border:"1px solid "+AM+"25",borderRadius:4,fontWeight:500}}>Enterprise</span></div><p style={{fontSize:15,color:MT,lineHeight:1.75}}>One of the world's largest Electronic Shelf Label companies. Sevyn8 platform deployed across their AI-at-Edge retail infrastructure combining ESL, RFID, and camera intelligence into a unified solution.</p></div></Rv><Rv d={0.08}><div style={{padding:24,borderRadius:12,border:"1px solid "+BD,background:BG}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10}}><span style={{fontSize:18,fontWeight:700}}>Premium Fashion Retailer</span><span style={{fontSize:10,color:AM,padding:"3px 10px",border:"1px solid "+AM+"25",borderRadius:4,fontWeight:500}}>Enterprise</span></div><p style={{fontSize:15,color:MT,lineHeight:1.75}}>A global-scale premium fashion retail brand. Sevyn8 powers in-store analytics including footfall, conversion tracking, and loss prevention across their retail network.</p></div></Rv></div></Rv></Sc>
    <Sc bt><Rv><div style={{textAlign:"center"}}><button style={bn} onClick={function(){p.go("contact")}}>Become a partner {"→"}</button></div></Rv></Sc></div>}

function AboutPg(){return <div style={{paddingTop:80}}>
  <Sc><Rv><Tg>Our Story</Tg><h1 style={{...hd,fontSize:46,fontWeight:700,lineHeight:1.06,marginBottom:22,maxWidth:560}}>Seven layers of intelligence. The eighth is infinity.</h1><p style={{fontSize:18,color:MT,lineHeight:1.85,maxWidth:560}}>The name encodes the thesis. Seven capabilities no single competitor holds. An eighth element &mdash; system-wide learning &mdash; that ensures the gap only widens.</p></Rv></Sc>

  <Sc bg={B2} bt><Rv><Tg c={T}>The sevyn</Tg><h2 style={{...hd,fontSize:34,fontWeight:700,marginBottom:20}}>The full stack. All seven.</h2></Rv>
    <Rv d={0.1}><p style={{fontSize:17,color:MT,lineHeight:1.85,marginBottom:20,maxWidth:640}}>Edge AI requires seven capabilities simultaneously: SoC access, firmware and HAL, AI/ML models, manufacturing, supply chain, go-to-market, and ecosystem. Chip companies own silicon but can't build products. ODMs manufacture but can't write AI. Software startups have models but no hardware DNA. No other company in Indian edge AI holds all seven. Sevyn8 does.</p></Rv>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(125px,1fr))",gap:8}}>{["SoC access","Firmware + HAL","AI/ML models","Manufacturing","Supply chain","Go-to-market","Ecosystem"].map(function(f,i){return <Rv key={i} d={.05+i*.04}><div style={{padding:14,borderRadius:7,border:"1px solid "+T+"25",background:T+"08",textAlign:"center",fontSize:14,fontWeight:500,color:T}}>{f}</div></Rv>})}</div>
  </Sc>

  <Sc bt><Rv><Tg c={AM}>The origin</Tg><h2 style={{...hd,fontSize:34,fontWeight:700,marginBottom:20}}>Forged at Motorola.</h2></Rv>
    <Rv d={0.1}><p style={{fontSize:17,color:MT,lineHeight:1.85,marginBottom:18,maxWidth:640}}>The conviction that you need all seven didn't come from a whiteboard. It came from scars. The founding team met in the Motorola trenches &mdash; building Motorola India into the number two mobile brand. That era was a masterclass in full-stack ownership: hardware, software, supply chain, GTM, and ecosystem held together.</p></Rv>
    <Rv d={0.15}><p style={{fontSize:17,color:MT,lineHeight:1.85,maxWidth:640}}>They also watched what happened when the stack fragmented. When brilliant technology died in the gap between "it works in the lab" and "it ships at scale." That experience became the founding DNA. You cannot half-build an edge platform. You either hold all seven, or you're building on someone else's foundation.</p></Rv>
  </Sc>

  <Sc bg={B2} bt><Rv><Tg c={AM}>The eight</Tg><h2 style={{...hd,fontSize:34,fontWeight:700,marginBottom:20}}>The compounding layer.</h2></Rv>
    <Rv d={0.1}><p style={{fontSize:17,color:MT,lineHeight:1.85,marginBottom:18,maxWidth:640}}>Six layers in the platform. Seven capabilities across the company. The eighth is what transforms Sevyn8 from a product into a platform: System-Wide Learning. It observes outcomes across every device, every customer, every vertical. The 500th device deployed is genuinely smarter than the 1st. Not better hardware &mdash; more knowledge.</p></Rv>
    <Rv d={0.15}><p style={{fontSize:17,color:MT,lineHeight:1.85,maxWidth:640}}>The "8" is also, visually, an infinity loop turned upright &mdash; &#8734;. Competitors improve per device. Sevyn8 improves per system. The gap widens with every deployment. It never stops.</p></Rv>
  </Sc>

  <Sc bt><Rv><Tg c={V}>The team</Tg><h2 style={{...hd,fontSize:34,fontWeight:700,marginBottom:20}}>Built across two decades. Not assembled.</h2></Rv>
    <Rv d={0.1}><p style={{fontSize:17,color:MT,lineHeight:1.85,marginBottom:20,maxWidth:640}}>The founding team brings combined experience from Intel, Motorola, Qualcomm, OnePlus, Sony, Honeywell, ABB, IBM, and Micron. Over &#8377;500 Cr in hardware categories built, launched, and scaled. The leadership spans SoC architecture, firmware engineering, AI/ML research, vision science, go-to-market, and ecosystem partnerships &mdash; each person mapped to a layer of the stack.</p></Rv>
    <Rv d={0.15}><p style={{fontSize:17,color:T,fontWeight:500}}>Skills can be hired. Years of scars and playbooks can only be earned.</p></Rv>
  </Sc>

  <Sc bg={B2} bt><Rv><div style={{textAlign:"center",padding:"20px 0"}}><div style={{fontSize:12,textTransform:"uppercase",letterSpacing:3,color:T,fontWeight:600,marginBottom:14}}>The brand truth</div><p style={{...hd,fontSize:28,fontWeight:800}}>Sevyn is the full stack. <span style={{color:T}}>8 is what makes it compound.</span></p></div></Rv></Sc>

  <Sc bt><div style={{display:"flex",gap:48,flexWrap:"wrap",fontSize:16}}>{[{k:"Entity",v:"Sevyn8 Private Limited"},{k:"HQ",v:"New Delhi, India"},{k:"Status",v:"DPIIT Recognised Startup"}].map(function(i){return <div key={i.k}><div style={{fontSize:11,color:DM,textTransform:"uppercase",letterSpacing:1,marginBottom:4}}>{i.k}</div><div style={{fontWeight:500}}>{i.v}</div></div>})}</div></Sc>
</div>}

function ContactPg(){var t2=useState("enterprise"),ty=t2[0],is2={fontFamily:"inherit",fontSize:16,padding:"14px 18px",background:B2,border:"1px solid "+BD,borderRadius:7,color:TX,outline:"none",width:"100%"};
  var ph=ty==="enterprise"?"Tell us about your deployment needs, store/site count, and current camera infrastructure...":ty==="oem"?"Tell us about your product line, annual shipment volume, and target AI features...":"How can we help?";
  return <div style={{paddingTop:80}}><Sc><Rv><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:60,alignItems:"start"}}><div><Tg>Contact</Tg><h1 style={{...hd,fontSize:44,fontWeight:700,marginBottom:18}}>Start the conversation.</h1><p style={{fontSize:17,color:MT,lineHeight:1.8,marginBottom:36}}>Enterprise deployment. OEM integration. Platform evaluation.</p><div style={{fontSize:16,color:MT,lineHeight:1.8}}><div style={{fontSize:11,color:DM,textTransform:"uppercase",letterSpacing:1,marginBottom:5}}>Email</div><div style={{color:TX,fontWeight:500}}>hello@sevyn8.com</div><div style={{marginTop:18,fontSize:11,color:DM,textTransform:"uppercase",letterSpacing:1,marginBottom:5}}>Location</div><div>New Delhi, India</div></div></div><div><div style={{display:"flex",gap:6,marginBottom:18}}>{[["enterprise","Enterprise"],["oem","OEM Partner"],["general","General"]].map(function(x){return <button key={x[0]} onClick={function(){t2[1](x[0])}} style={{padding:"8px 18px",borderRadius:6,fontSize:14,fontWeight:500,fontFamily:"inherit",border:"1px solid "+(ty===x[0]?T:BD),background:ty===x[0]?T+"12":"transparent",color:ty===x[0]?T:MT,cursor:"pointer"}}>{x[1]}</button>})}</div><div style={{display:"flex",flexDirection:"column",gap:10}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><input placeholder="Name" style={is2} /><input placeholder="Email" style={is2} /></div><input placeholder="Company" style={is2} />{ty==="enterprise"&&<input placeholder="Industry (Smart Home, Retail, Fleet, Food & Cold Storage)" style={is2} />}{ty==="oem"&&<input placeholder="Annual device volume" style={is2} />}<textarea placeholder={ph} rows={4} style={{...is2,resize:"vertical"}} /><button style={{...bn,alignSelf:"flex-start"}}>Send message {"→"}</button></div></div></div></Rv></Sc></div>}

function Nav(p){var pg=p.pg,go=p.go,s2=useState(false),d2=useState(null);
  useEffect(function(){var h=function(){s2[1](window.scrollY>40)};window.addEventListener("scroll",h);return function(){window.removeEventListener("scroll",h)}},[]);
  var nl=function(l,t){return <span onClick={function(){go(t)}} style={{fontSize:14,fontWeight:500,color:pg===t?T:MT,cursor:"pointer"}}>{l}</span>};
  return <nav style={{position:"fixed",top:0,left:0,right:0,zIndex:999,padding:"0 40px",background:s2[0]?"rgba(6,8,16,.94)":"transparent",backdropFilter:s2[0]?"blur(20px)":"none",borderBottom:s2[0]?"1px solid "+BD:"none",transition:"all .3s"}}><div style={{maxWidth:1200,margin:"0 auto",display:"flex",alignItems:"center",justifyContent:"space-between",height:60}}><div onClick={function(){go("home")}} style={{cursor:"pointer",display:"flex",alignItems:"center",gap:8}}><div style={{width:26,height:26,borderRadius:5,background:"linear-gradient(135deg,"+T+","+BL+")",display:"flex",alignItems:"center",justifyContent:"center",fontSize:11,fontWeight:800,color:BG}}>S8</div><span style={{fontSize:16,fontWeight:800,letterSpacing:2}}>SEVYN8</span></div><div style={{display:"flex",alignItems:"center",gap:26}}>{nl("Platform","platform")}{nl("Edge AI Box","box")}<div style={{position:"relative"}} onMouseEnter={function(){d2[1]("s")}} onMouseLeave={function(){d2[1](null)}}><span style={{fontSize:14,fontWeight:500,color:pg.startsWith("sol-")?T:MT,cursor:"pointer",padding:"8px 0"}}>Solutions &#9662;</span>{d2[0]==="s"&&<div style={{position:"absolute",top:"100%",left:"50%",transform:"translateX(-50%)",paddingTop:8,zIndex:100}}><div style={{background:B2,border:"1px solid "+BD,borderRadius:10,padding:6,minWidth:280,boxShadow:"0 16px 48px rgba(0,0,0,.5)"}}>{SOL.map(function(s){return <div key={s.id} onClick={function(){go("sol-"+s.id)}} style={{padding:"10px 16px",borderRadius:7,cursor:"pointer",fontSize:14,color:TX}}>{s.n}<br/><span style={{fontSize:12,color:DM}}>{s.ln}</span></div>})}</div></div>}</div>{nl("Partners","partners")}<div style={{position:"relative"}} onMouseEnter={function(){d2[1]("c")}} onMouseLeave={function(){d2[1](null)}}><span style={{fontSize:14,fontWeight:500,color:["about","contact"].includes(pg)?T:MT,cursor:"pointer",padding:"8px 0"}}>Our Story &#9662;</span>{d2[0]==="c"&&<div style={{position:"absolute",top:"100%",right:0,paddingTop:8,zIndex:100}}><div style={{background:B2,border:"1px solid "+BD,borderRadius:10,padding:6,minWidth:150,boxShadow:"0 16px 48px rgba(0,0,0,.5)"}}>{[["Our Story","about"],["Contact","contact"]].map(function(x){return <div key={x[0]} onClick={function(){go(x[1])}} style={{padding:"10px 16px",borderRadius:7,cursor:"pointer",fontSize:14,color:TX}}>{x[0]}</div>})}</div></div>}</div><button style={{...bn,padding:"8px 20px",fontSize:13}} onClick={function(){go("contact")}}>Contact</button></div></div></nav>}

function Ft(){return <footer style={{borderTop:"1px solid "+BD,background:B2,padding:"36px 40px"}}><div style={{maxWidth:1200,margin:"0 auto",display:"flex",justifyContent:"space-between",alignItems:"center",fontSize:13,color:DM,flexWrap:"wrap",gap:12}}><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:20,height:20,borderRadius:4,background:"linear-gradient(135deg,"+T+","+BL+")",display:"flex",alignItems:"center",justifyContent:"center",fontSize:9,fontWeight:800,color:BG}}>S8</div><span style={{fontWeight:800,letterSpacing:2}}>SEVYN8</span></div><span>2026 Sevyn8 Private Limited &middot; New Delhi &middot; DPIIT Recognised</span></div></footer>}

export default function App(){
  var p2=useState("home"),pg=p2[0];
  useEffect(function(){var id="G-XXXXXXXXXX";var s=document.createElement("script");s.src="https://www.googletagmanager.com/gtag/js?id="+id;s.async=true;document.head.appendChild(s);window.dataLayer=window.dataLayer||[];function gtag(){window.dataLayer.push(arguments)}window.gtag=gtag;gtag("js",new Date());gtag("config",id)},[]);
  useEffect(function(){if(window.gtag)window.gtag("event","page_view",{page_title:pg,page_path:"/"+pg})},[pg]);
  useEffect(function(){document.title="Sevyn8 | AI at Edge Platform";[{name:"description",content:"Sevyn8 is an AI at Edge Platform. SoC-agnostic. Under 100ms inference, fully offline. Smart Home, Retail, Fleet, Cold Storage."},{name:"keywords",content:"edge AI, AI platform, edge computing, SoC agnostic, HAL, on-device AI, computer vision, IoT, fleet intelligence, OEM licensing, cold chain, food safety, smart home, retail analytics"},{property:"og:title",content:"Sevyn8 | Intelligence at the Edge"},{property:"og:description",content:"The AI at Edge Platform. Six layers. One device. Four industries."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"},{name:"robots",content:"index, follow"}].forEach(function(m){var el=document.createElement("meta");if(m.name)el.name=m.name;if(m.property)el.setAttribute("property",m.property);el.content=m.content;document.head.appendChild(el)})},[]);
  var go=useCallback(function(p){p2[1](p);window.scrollTo({top:0,behavior:"instant"})},[]);
  var C;if(pg==="home")C=<Home go={go}/>;else if(pg==="platform")C=<PlatPg go={go}/>;else if(pg==="box")C=<BoxPg go={go}/>;else if(pg==="partners")C=<PartPg go={go}/>;else if(pg==="about")C=<AboutPg />;else if(pg==="contact")C=<ContactPg />;else if(pg.indexOf("sol-")===0){var s=SOL.find(function(x){return "sol-"+x.id===pg});C=s?<SolPg s={s} go={go}/>:<Home go={go}/>}else C=<Home go={go}/>;
  return <div style={{minHeight:"100vh",background:BG,fontFamily:"'DM Sans',system-ui,sans-serif",WebkitFontSmoothing:"antialiased",color:TX,fontSize:16,lineHeight:1.65}}>
    <style dangerouslySetInnerHTML={{__html:"@import url('https://cdn.jsdelivr.net/npm/@fontsource-variable/outfit/index.min.css');@import url('https://cdn.jsdelivr.net/npm/@fontsource/dm-sans@5.0.3/400.css');@import url('https://cdn.jsdelivr.net/npm/@fontsource/dm-sans@5.0.3/500.css');@import url('https://cdn.jsdelivr.net/npm/@fontsource/dm-sans@5.0.3/700.css');*{margin:0;padding:0;box-sizing:border-box}::selection{background:#00D4AA;color:#060810}html{scroll-behavior:smooth}"}} />
    <Nav pg={pg} go={go}/><main key={pg}>{C}</main><Ft />
  </div>;
}
